import type { CancellationPolicy, ListingService, ReservationChannel, ReservationStatus, StaffRole } from "./types";
import { ApiError } from "./api";
import { PRODUCT } from "./product";

// All user-facing strings live here so the interface can be translated later.
export const fr = {
  common: {
    save: "Enregistrer",
    saved: "Modifications enregistrées",
    never: "Jamais",
    loading: "Chargement…",
  },
  roles: {
    manager: "Gérant",
    agent: "Agent d'accueil",
    driver: "Chauffeur navette",
    valet: "Voiturier",
  } satisfies Record<StaffRole, string>,
  errors: {
    required: "Champ obligatoire.",
    too_long: "Texte trop long.",
    invalid_email: "Adresse email invalide.",
    invalid_role: "Rôle invalide.",
    integer: "Nombre entier attendu.",
    min_1: "Doit être au moins 1.",
    too_large: "Valeur trop grande.",
    margin_range: "Entre 0 et 50 %.",
    shuttle_range: "Entre 1 et 120 minutes.",
    password_too_short: "Au moins 10 caractères.",
    invalid_credentials: "Email ou mot de passe incorrect.",
    too_many_attempts: "Trop de tentatives. Réessayez dans 15 minutes.",
    too_many_requests: "Trop de demandes. Réessayez dans un instant.",
    email_taken: "Cette adresse email est déjà utilisée.",
    cannot_demote_self: "Vous ne pouvez pas retirer vos propres droits de gérant ni désactiver votre compte.",
    last_manager: "Il doit rester au moins un gérant actif.",
    wrong_current_password: "Mot de passe actuel incorrect.",
    forbidden: "Vous n'avez pas accès à cette action.",
    not_found: "Élément introuvable.",
    unauthorized: "Votre session a expiré. Reconnectez-vous.",
    validation_failed: "Certains champs sont à corriger.",
    network: "Le serveur ne répond pas. Vérifiez votre connexion.",
    invalid_datetime: "Date ou heure invalide.",
    return_before_arrival: "Le retour doit être après l'arrivée.",
    stay_too_long: "Séjour de plus de 90 jours.",
    passengers_range: "Entre 1 et 9 passagers.",
    invalid_phone: "Numéro de téléphone invalide.",
    invalid_plate: "Plaque invalide.",
    invalid_flight: "Numéro de vol invalide (ex. TO 3627).",
    invalid_channel: "Canal invalide.",
    invalid_status: "Statut invalide.",
    invalid_transition: "Ce changement de statut n'est pas possible.",
    overbooked: "Au moins une nuit est complète.",
    reservation_closed: "Cette réservation est close.",
    unrecognised_email: "Ce texte ne ressemble à aucun mail de comparateur connu.",
    already_imported: "Cette réservation a déjà été importée.",
    min_0: "Doit être positif.",
    invalid_slug: "Lettres minuscules, chiffres et tirets seulement (ex. parking-demo).",
    slug_taken: "Cette adresse est déjà prise par un autre parking.",
    unknown_airport: "Aéroport inconnu.",
    invalid_url: "Adresse https:// invalide.",
    invalid_service: "Service inconnu.",
    invalid_policy: "Politique d'annulation inconnue.",
    number: "Nombre attendu.",
    pricing_required: "Enregistrez d'abord vos tarifs : une fiche sans prix ne peut pas être mise en ligne.",
    duplicate_days: "Deux forfaits ont la même durée.",
    unknown: "Une erreur est survenue. Réessayez.",
    geo_unavailable: "Le service de l'IGN ne répond pas. Réessayez dans un instant.",
    geo_timeout: "Le service de l'IGN a mis trop de temps à répondre. Réessayez.",
    bbox_too_large: "Zoomez davantage pour afficher les parkings.",
    invalid_geometry: "Forme invalide.",
    too_many_vertices: "Forme trop détaillée (trop de sommets).",
    too_many_items: "Trop d'éléments.",
    invalid_item: "Élément invalide.",
    scale_range: "Échelle entre × 0,5 et × 2.",
  } as Record<string, string>,
  login: {
    title: "Connexion",
    subtitle: "Espace professionnel",
    email: "Email",
    password: "Mot de passe",
    submit: "Se connecter",
    passwordChanged: "Mot de passe modifié. Reconnectez-vous.",
  },
  nav: {
    planning: "Planning",
    plazo: "Sur Plazo",
    reservations: "Réservations",
    dashboard: "Tableau de bord",
    parking: "Parking",
    team: "Équipe",
    account: "Mon compte",
    logout: "Se déconnecter",
    internalTool: "Outil interne",
  },
  dashboard: {
    hello: (name: string) => `Bonjour ${name}`,
    totalCapacity: "Places au total",
    bookableCapacity: "Places réservables",
    safetyMargin: "Marge de sécurité",
    shuttle: "Trajet navette",
    minutes: (n: number) => `${n} min`,
    places: (n: number) => `${n} place${n > 1 ? "s" : ""}`,
    bookableHelp: "Capacité totale moins la marge de sécurité : c'est le plafond utilisé contre la surréservation.",
  },
  parking: {
    title: "Réglages du parking",
    name: "Nom du parking",
    address: "Adresse",
    totalCapacity: "Nombre de places au total",
    safetyMarginPct: "Marge de sécurité (%)",
    safetyMarginHelp: "Part des places jamais proposées à la réservation (imprévus, prolongations).",
    shuttleTravelMinutes: "Durée du trajet navette (minutes)",
    shuttleHelp: "Entre le parking et le terminal.",
    bookablePreview: (n: number) => `Places réservables avec ces réglages : ${n}`,
  },
  team: {
    title: "Équipe",
    add: "Ajouter un membre",
    name: "Nom",
    email: "Email",
    phone: "Téléphone",
    role: "Rôle",
    active: "Actif",
    inactive: "Désactivé",
    lastLogin: "Dernière connexion",
    password: "Mot de passe provisoire",
    passwordHelp: "À communiquer à la personne, qui le changera dans « Mon compte ».",
    create: "Créer le compte",
    created: "Compte créé",
    updated: "Membre mis à jour",
    deactivate: "Désactiver",
    reactivate: "Réactiver",
    resetPassword: "Nouveau mot de passe",
    passwordReset: "Mot de passe réinitialisé. Ses sessions ont été fermées.",
    you: "vous",
  },
  account: {
    title: "Mon compte",
    currentPassword: "Mot de passe actuel",
    newPassword: "Nouveau mot de passe",
    submit: "Changer le mot de passe",
  },
  status: {
    upcoming: "Attendu",
    arrived: "Sur place",
    shuttled_out: "En navette",
    return_requested: "Retour demandé",
    returned: "Rendu",
    cancelled: "Annulé",
    no_show: "Non venu",
  } satisfies Record<ReservationStatus, string>,
  statusAction: {
    upcoming: "Remettre en attente",
    arrived: "Enregistrer l'arrivée",
    shuttled_out: "Parti en navette",
    return_requested: "Client de retour",
    returned: "Véhicule rendu",
    cancelled: "Annuler la réservation",
    no_show: "Marquer non venu",
  } satisfies Record<ReservationStatus, string>,
  channels: {
    website: "Site",
    phone: "Téléphone",
    counter: "Comptoir",
    aggregator: "Comparateur",
    import: "Import",
    // Booked by a traveller on the public site.
    plazo: PRODUCT.name,
  } satisfies Record<ReservationChannel, string>,
  planning: {
    today: "Aujourd'hui",
    previousDay: "Jour précédent",
    nextDay: "Jour suivant",
    newReservation: "+ Réservation",
    nightsTitle: "Occupation des nuits",
    overbookedBy: (n: number) => `Surréservé +${n}`,
    almostFull: "Presque plein",
    free: (n: number) => `${n} libre${n > 1 ? "s" : ""}`,
    arrivals: "Arrivées",
    returns: "Retours",
    arrivalsCount: (total: number, here: number) => `${total} · ${here} sur place`,
    noArrival: "Aucune arrivée ce jour.",
    noReturn: "Aucun retour ce jour.",
    pax: (n: number) => `${n} pers.`,
    from: (city: string) => `de ${city}`,
  },
  reservation: {
    newTitle: "Nouvelle réservation",
    editTitle: "Modifier la réservation",
    arrival: "Arrivée",
    return: "Retour",
    date: "Date",
    time: "Heure",
    customerName: "Client",
    customerPhone: "Téléphone",
    customerEmail: "Email (facultatif)",
    email: "Email",
    plate: "Plaque",
    returnFlight: "Vol retour",
    returnFlightHelp: "Pour suivre l'atterrissage (jalon 5).",
    passengers: "Passagers",
    channel: "Canal",
    channelDetail: "Nom du comparateur",
    notes: "Notes",
    nights: (n: number) => `${n} nuit${n > 1 ? "s" : ""}`,
    save: "Enregistrer",
    saved: "Réservation enregistrée",
    full: (days: string) => `Complet : ${days}.`,
    fullHelp: "Refusée sur la page publique. Au comptoir, vous pouvez l'enregistrer quand même en connaissance de cause.",
    fullNoForce: "Seul un agent ou le gérant peut l'enregistrer quand même.",
    force: "Enregistrer quand même (surréservation)",
    available: (n: number) => `Disponible : au moins ${n} place${n > 1 ? "s" : ""} libre${n > 1 ? "s" : ""} chaque nuit.`,
    reference: "Référence",
    overbookedBadge: "Surréservation",
    edit: "Modifier",
    cancelEdit: "Annuler la modification",
    status: "Statut",
    journey: "Étapes",
    contact: "Contact",
    stay: "Séjour",
    created: "Créée le",
    searchPlaceholder: "Plaque, nom, téléphone ou référence",
    search: "Rechercher",
    noResult: "Aucune réservation trouvée.",
    previous: "Précédent",
    next: "Suivant",
    page: (p: number, total: number) => `Page ${p} / ${total}`,
    listTitle: "Réservations",
    back: "Retour",
  },
  importEmail: {
    title: "Importer un mail de comparateur",
    known: "Reconnus : Allopark · bientôt Parkos, Onepark",
    pasteLabel: "Collez le mail de confirmation",
    pastePlaceholder: "Copiez tout le mail (Ctrl+A puis Ctrl+C dans la messagerie) et collez-le ici.",
    analyse: "Analyser",
    analyseAgain: "Analyser à nouveau",
    analysing: "Lecture du mail…",
    nothingSaved: "Rien n'est enregistré avant validation",
    empty: "Le résultat de la lecture s'affichera ici.",
    found: "Trouvé",
    toComplete: " · à compléter",
    arrival: "Arrivée",
    return: "Retour",
    customer: "Client",
    phone: "Téléphone",
    email: "Email",
    plate: "Plaque",
    flight: "Vol retour",
    passengers: "Passagers",
    price: "Prix payé",
    datesMissing: "Dates introuvables dans le mail : ouvrez le formulaire complet pour les saisir.",
    duplicate: (ref: string) => `Déjà importée : réservation ${ref}.`,
    openDuplicate: "Voir la réservation",
    openForm: "Ouvrir dans le formulaire complet",
    create: "Créer la réservation",
    created: (ref: string) => `Réservation ${ref} créée. Collez le mail suivant.`,
    openCreated: "Voir",
    nightsAvailable: (nights: number, free: number) =>
      `${nights} nuit${nights > 1 ? "s" : ""} · disponible : au moins ${free} place${free > 1 ? "s" : ""} libre${free > 1 ? "s" : ""} chaque nuit.`,
    action: "Importer un mail",
  },
  plazo: {
    tabs: { listing: "Ma fiche", pricing: "Mes tarifs", payouts: "Mes reversements" },
    soon: "Bientôt",
    online: "En ligne",
    draft: "Brouillon",
    visible: "Visible sur Plazo",
    hidden: "Masquée sur Plazo",
    publish: "Mettre en ligne",
    unpublish: "Retirer de Plazo",
    published: "Votre fiche est en ligne sur Plazo.",
    unpublished: "Votre fiche est retirée de Plazo.",
    saved: "Fiche enregistrée",
    airport: "Aéroport",
    title: "Nom affiché",
    slug: "Adresse de la page",
    description: "Présentation",
    services: "Services",
    shuttleMinutes: "Navette (min)",
    distanceKm: "Distance (km)",
    openingHours: "Horaires",
    openingHoursPlaceholder: "24h/24",
    cancellation: "Annulation",
    photos: "Photos (la première sert de vignette)",
    photoUrl: "Adresse de la photo (https://…)",
    addPhoto: "+ Photo",
    removePhoto: "Retirer la photo",
    photosHelp: "Collez l'adresse d'une photo en ligne. L'envoi de fichiers depuis l'ordinateur arrive bientôt.",
    preview: "Aperçu dans les résultats Plazo",
    from: (price: string) => `dès ${price}`,
    noPrice: "prix à définir",
    newOnPlazo: "Nouveau sur Plazo",
    see: "Voir",
    viewPage: "Voir ma page",
    save: "Enregistrer",
    pricingIntro: "Un séjour paie le forfait le moins cher qui le couvre. Les jours se comptent du jour d'arrivée au jour de retour inclus.",
    duration: "Durée",
    priceAll: "Prix tout compris",
    upTo: "Jusqu'à",
    dayUnit: (n: number) => (n > 1 ? "jours" : "jour"),
    removeTier: "Supprimer ce forfait",
    addTier: "+ Ajouter un forfait",
    extraDay: (days: number) => `Au-delà de ${days} jour${days > 1 ? "s" : ""}, chaque jour en plus :`,
    extraDayNoTier: "Chaque jour au-delà du plus long forfait :",
    extraDayLabel: "Prix du jour supplémentaire",
    savePricing: "Enregistrer les tarifs",
    pricingSaved: "Tarifs enregistrés",
    unsaved: "Modifié · non enregistré",
    simulationTitle: "Ce que paie le voyageur",
    simDays: (n: number) => `${n} j`,
    simTier: (n: number) => `Forfait ${n} jour${n > 1 ? "s" : ""}`,
    simExtra: (base: number, extra: number, price: string) => `${base} jours + ${extra} × ${price}`,
    simNone: "Pas de prix : ajoutez un forfait plus long ou un prix par jour",
    commission: (pct: string) =>
      `Sur une réservation payée en ligne, Plazo retient sa commission (${pct} %) et vous reverse le reste. Les réservations au comptoir, par téléphone ou via les comparateurs ne sont pas concernées.`,
    commissionUnset:
      "Sur une réservation payée en ligne, Plazo retient une commission (taux à convenir) et vous reverse le reste. Les réservations au comptoir, par téléphone ou via les comparateurs ne sont pas concernées.",
    invalidPrice: "Prix invalide (ex. 34,99).",
    invalidDays: "Entre 1 et 90 jours.",
  },
  services: {
    shuttle: "Navette",
    open_24h: "24h/24",
    fenced: "Clôturé",
    cctv: "Vidéosurveillance",
    valet: "Voiturier",
    covered: "Couvert",
    ev_charging: "Recharge électrique",
  } satisfies Record<ListingService, string>,
  cancellation: {
    free_24h: ["Gratuite 24 h avant", "remboursement total"],
    free_48h: ["Gratuite 48 h avant", "remboursement total"],
    free_until_arrival: ["Jusqu'à l'arrivée", "remboursement total"],
    non_refundable: ["Non remboursable", ""],
  } satisfies Record<CancellationPolicy, [string, string]>,
  cancellationShort: {
    free_24h: "Annulation gratuite 24 h",
    free_48h: "Annulation gratuite 48 h",
    free_until_arrival: "Annulation gratuite",
    non_refundable: "Non remboursable",
  } satisfies Record<CancellationPolicy, string>,
  capacity: {
    brandTag: "Outil interne",
    tab: "Estimateur de capacité",
    backToPro: "Espace pro",
    steps: ["Repérer le terrain", "Découper en zones", "Estimer la capacité"],
    study: "Étude",
    rename: "Renommer l'étude",
    saving: "Enregistrement…",
    saved: "Enregistré",
    saveError: "Non enregistré",
    // Study list
    listTitle: "Mes études",
    listSubtitle: "Estimations de capacité des terrains des loueurs (outil réservé à la plateforme).",
    newStudy: "Nouvelle étude",
    newStudyName: "Nouvelle étude",
    empty: "Aucune étude pour l'instant.",
    colName: "Étude",
    colParcels: "Parcelles",
    colRange: "Fourchette",
    colUpdated: "Mise à jour",
    open: "Ouvrir",
    delete: "Supprimer",
    confirmDelete: (name: string) => `Supprimer l'étude « ${name} » ?`,
    deleted: "Étude supprimée",
    rangeShort: (a: number, b: number) => `${a} à ${b} voitures`,
    // Step 1
    tools: { pan: "Déplacer", addVertex: "Sommet +", removeVertex: "Sommet −", cut: "Exclure une partie", draw: "Dessiner" },
    toolHelp: {
      pan: "Cliquez sur le terrain pour ajouter ou retirer sa parcelle cadastrale.",
      addVertex: "Faites glisser un sommet, ou un point milieu pour en ajouter un.",
      removeVertex: "Cliquez sur un sommet pour le retirer.",
      cut: "Dessinez la partie à retirer du contour ; double-cliquez pour terminer.",
      draw: "Cliquez chaque coin du terrain ; double-cliquez pour terminer.",
      dimension: "Cliquez deux sommets du contour, puis saisissez la distance mesurée sur place.",
    },
    address: "Adresse ou point sur la carte",
    addressPlaceholder: "Adresse, commune ou « latitude, longitude »",
    pointLabel: (lat: number, lon: number) => `Point ${lat.toFixed(5)}, ${lon.toFixed(5)}`,
    searching: "Recherche…",
    noResult: "Aucune adresse trouvée.",
    outline: "Contour proposé",
    noOutline: "Pas encore de contour",
    noOutlineHelp: "Cliquez sur le terrain : sa parcelle cadastrale est proposée comme contour. Cliquez les parcelles voisines pour les ajouter.",
    drawByHand: "ou dessiner le contour à la main",
    parcelsLabel: (ids: string) => `Parcelles cadastrales ${ids}`,
    clippedWithParking: "recoupées avec la surface de parking repérée par l'IGN (BD TOPO)",
    editedByHand: "contour corrigé à la main",
    drawnByHand: "Contour dessiné à la main",
    clipToParking: "Recouper avec le parking BD TOPO",
    parcelLoading: "Recherche de la parcelle…",
    parcelNone: "Aucune parcelle cadastrale à cet endroit.",
    sources: "Sources affichées",
    sourcePhoto: "Photo aérienne IGN",
    sourcePhotoHelp: (date: string) => `20 cm · ${date} · licence ouverte`,
    sourceParcels: "Parcelles cadastrales",
    sourceParcelsHelp: "API Carto · cadastre",
    sourceParkings: "Parkings BD TOPO",
    sourceParkingsHelp: "IGN · surfaces de parking",
    parkingsZoom: "zoomez pour les afficher",
    help: "Corrigez le contour à la souris (déplacer un sommet, en ajouter, en retirer), puis saisissez une cote mesurée sur place pour caler l'échelle.",
    addDimension: "Ajouter une cote",
    validateOutline: "Valider le contour",
    dimension: "Cote mesurée",
    dimensionPick: (n: number) => (n === 0 ? "Cliquez le premier sommet." : "Cliquez le second sommet."),
    dimensionOnMap: (m: string) => `Sur la photo : ${m} m`,
    dimensionMeasured: "Distance mesurée sur place (m)",
    apply: "Appliquer",
    cancel: "Annuler",
    scale: "Échelle",
    scaleNone: "× 1 (aucune cote saisie)",
    scaleValue: (factor: string, measured: string) => `× ${factor} · cote de ${measured} m mesurée sur place`,
    removeScale: "Retirer la cote",
    // Step 2
    zonesTitle: (area: string) => `Zones du terrain · ${area} m²`,
    zoneName: (letter: string) => `Zone ${letter}`,
    zoneSubtitle: "stationnement",
    zoneDetail: "voitures légères",
    addZone: "+ Zone de stationnement",
    addExclusion: "+ Partie exclue (bâtiment, arbre, poteau)",
    chooseExclusion: "Quelle partie exclure ?",
    exclusionKinds: {
      building: "Bâtiment",
      reception: "Accueil et remise des clés",
      shuttle_lane: "Voie navette",
      tree: "Arbre",
      post: "Poteau",
      other: "Autre partie",
    },
    exclusionSubtitle: {
      building: "exclu du stationnement",
      reception: "exclue du stationnement",
      shuttle_lane: "circulation, exclue",
      tree: "dégagement autour du tronc",
      post: "dégagement autour",
      other: "exclue du stationnement",
    },
    laneWidth: "Largeur (m)",
    clearance: "Dégagement (m)",
    drawZoneHelp: "Dessinez la zone sur la carte ; double-cliquez pour terminer.",
    drawLineHelp: "Tracez l'axe de la voie ; double-cliquez pour terminer.",
    drawPointHelp: "Cliquez l'emplacement sur la carte.",
    editHelp: "Faites glisser les sommets de l'élément sélectionné.",
    remove: "Retirer",
    back: "Retour",
    estimate: "Estimer la capacité",
    noZone: "Ajoutez au moins une zone de stationnement.",
    // Step 3
    compared: (zone: string, area: string) => `${zone} · ${area} m² · 3 dispositions comparées`,
    zonesCount: (n: number) => `${n} zones`,
    computing: "Calcul des dispositions…",
    layouts: {
      selfPark: "Clients garés seuls",
      valet24: "Voiturier · files de 2 à 4",
      valet5: "Voiturier · files de 5",
    },
    cars: "voitures",
    perCar: (m2: string) => `${m2} m² par voiture`,
    selfParkDetail: (slot: string, aisle: string, endStalls: boolean) =>
      `Épi 90°, places ${slot} m, allées ${aisle} m${endStalls ? ", places en bout d'allée" : ""}`,
    valet24Detail: (pattern: string, depth: number) => `Blocs ${pattern}, aucune voiture à plus de ${depth} rangs d'une allée`,
    valet5Detail: (pattern: string) => `Blocs ${pattern} : plus dense, mais fragile en cas de retour avancé`,
    aisle: "allée",
    range: (a: number, b: number) => `${a} à ${b} voitures`,
    rangeLabel: "Fourchette à annoncer : ",
    ceiling: (n: number) => `Plafond théorique sans aucune allée : ${n}.`,
    photoCheck: "Contrôle sur la photo : ",
    photoCounted: (n: number) => `≈ ${n} voitures comptées`,
    photoOn: (date: string) => ` le ${date} (comptage à la main).`,
    photoTodo: "compter les voitures sur la photo",
    settings: "Réglages",
    overlaySlot: "Place",
    overlayAisle: "Allée",
    overlayOrientation: "Orientation",
    overlayDepth: "Profondeur max",
    auto: "auto",
    selfParkSlot: "Place client (largeur × longueur, m)",
    valetSlot: "Place voiturier (largeur × longueur, m)",
    aisleWidth: "Largeur d'allée (m)",
    maxDepth: "Profondeur max entre deux allées",
    setback: "Retrait en bordure (m)",
    orientation: "Orientation (°, vide = auto)",
    endStalls: "Places en bout d'allée (clients)",
    crossAisles: "Allées transversales aux extrémités",
    export: "Exporter (GeoJSON)",
    createPlan: "Créer le plan du parking",
    soon: "Bientôt (jalon 4)",
    noResult3: "Aucune place ne tient : vérifiez les zones et les réglages.",
    // Photo check
    photoTitle: "Contrôle sur la photo",
    photoHelp: (date: string) => `voitures comptées sur la photo IGN du ${date} (cliquez sur chaque voiture ; cliquez à nouveau pour la retirer)`,
    occupied: (area: string) => `Surface occupée : ${area} m²`,
    observed: "Constaté : ",
    perCarSuffix: " par voiture",
    estimated: "Estimé (voiturier 2–4) : ",
    photoNote:
      "La photo date de juillet 2023, un jour quelconque : elle montre un remplissage, pas une capacité maximale. À comparer avec le pic réel donné par le gérant.",
    clearCount: "Effacer le comptage",
    save: "Enregistrer",
    backToEstimate: "Retour à l'estimation",
  },
  notFound: {
    title: "Page introuvable",
    back: "Retour au tableau de bord",
  },
};

export function errorMessage(code: string | undefined): string {
  if (!code) return fr.errors.unknown;
  return fr.errors[code] ?? fr.errors.unknown;
}

/** French message for any error thrown by the API client. */
export function describeError(error: unknown): string {
  if (error instanceof ApiError) return errorMessage(error.code);
  if (error instanceof TypeError) return fr.errors.network;
  return fr.errors.unknown;
}

export const dateTime = new Intl.DateTimeFormat("fr-FR", { dateStyle: "short", timeStyle: "short", timeZone: "Europe/Paris" });
