import type {
  CancellationPolicy,
  ListingService,
  ListingStatus,
  PayoutSchedule,
  ReservationChannel,
  PlatformAudience,
  ReservationStatus,
  ShuttleStopKind,
  SmsMode,
  StaffRole,
  AlertKind,
  ShuttleDirection,
  WaveState,
} from "./types";
import { ApiError } from "./api";
import { PRODUCT } from "./product";

// All user-facing strings live here so the interface can be translated later.
export const fr = {
  common: {
    close: "Fermer",
    save: "Enregistrer",
    saved: "Modifications enregistrées",
    never: "Jamais",
    loading: "Chargement…",
  },
  roles: {
    manager: "Gérant",
    agent: "Agent d'accueil",
    driver: "Chauffeur navette",
    valet: "Voiturier",
  } satisfies Record<StaffRole, string>,
  errors: {
    required: "Champ obligatoire.",
    too_long: "Texte trop long.",
    invalid_lat: "Position invalide.",
    invalid_lng: "Position invalide.",
    invalid_email: "Adresse email invalide.",
    invalid_role: "Rôle invalide.",
    integer: "Nombre entier attendu.",
    min_1: "Doit être au moins 1.",
    too_large: "Valeur trop grande.",
    margin_range: "Entre 0 et 50 %.",
    shuttle_range: "Entre 1 et 120 minutes.",
    password_too_short: "Au moins 10 caractères.",
    invalid_credentials: "Email ou mot de passe incorrect.",
    too_many_attempts: "Trop de tentatives. Réessayez dans 15 minutes.",
    too_many_requests: "Trop de demandes. Réessayez dans un instant.",
    daily_limit: "Limite atteinte : deux envois aux voyageurs par jour au plus.",
    invalid_audience: "Destinataires inconnus.",
    email_taken: "Cette adresse email est déjà utilisée.",
    cannot_demote_self:
      "Vous ne pouvez pas retirer vos propres droits de gérant ni désactiver votre compte.",
    last_manager: "Il doit rester au moins un gérant actif.",
    wrong_current_password: "Mot de passe actuel incorrect.",
    forbidden: "Vous n'avez pas accès à cette action.",
    trip_already_running: "Un trajet est déjà en cours : terminez-le avant d'en démarrer un autre.",
    trip_not_running: "Ce trajet est terminé.",
    invalid_passengers: "Un des clients ne peut pas monter dans cette navette (statut changé ?). Actualisez la liste.",
    already_on_trip: "Un des clients est déjà sur un trajet en cours.",
    invalid_direction: "Sens du trajet invalide.",
    position_too_old: "Position trop ancienne : nouvel essai en cours.",
    too_many_positions: "Patientez quelques secondes.",
    not_found: "Élément introuvable.",
    unauthorized: "Votre session a expiré. Reconnectez-vous.",
    validation_failed: "Certains champs sont à corriger.",
    network: "Le serveur ne répond pas. Vérifiez votre connexion.",
    invalid_datetime: "Date ou heure invalide.",
    return_before_arrival: "Le retour doit être après l'arrivée.",
    stay_too_long: "Séjour de plus de 90 jours.",
    passengers_range: "Entre 1 et 9 passagers.",
    invalid_phone: "Numéro de téléphone invalide.",
    invalid_plate: "Plaque invalide.",
    invalid_flight: "Numéro de vol invalide (ex. TO 3627).",
    invalid_channel: "Canal invalide.",
    invalid_status: "Statut invalide.",
    invalid_transition: "Ce changement de statut n'est pas possible.",
    invalid_seats: "Entre 1 et 60 places.",
    invalid_driver: "Ce chauffeur ne fait pas partie de l'équipe.",
    vehicle_out_of_service: "Ce véhicule est hors service.",
    vehicle_taken: "Ce véhicule est déjà pris aujourd'hui par un collègue.",
    invalid_stop: "Cette desserte n'existe pas (ou plus).",
    too_many_passengers: "Plus de passagers que de places dans ce véhicule.",
    overbooked: "Au moins une nuit est complète.",
    reservation_closed: "Cette réservation est close.",
    unrecognised_email:
      "Ce texte ne ressemble à aucun mail de comparateur connu.",
    already_imported: "Cette réservation a déjà été importée.",
    min_0: "Doit être positif.",
    invalid_slug:
      "Lettres minuscules, chiffres et tirets seulement (ex. parking-demo).",
    slug_taken: "Cette adresse est déjà prise par un autre parking.",
    unknown_airport: "Aéroport inconnu.",
    invalid_url: "Adresse web invalide (http:// ou https://).",
    invalid_service: "Service inconnu.",
    invalid_policy: "Politique d'annulation inconnue.",
    number: "Nombre attendu.",
    pricing_required:
      "Enregistrez d'abord vos tarifs : une fiche sans prix ne peut pas être envoyée en validation.",
    duplicate_days: "Deux forfaits ont la même durée.",
    unknown: "Une erreur est survenue. Réessayez.",
    geo_unavailable:
      "Le service de l'IGN ne répond pas. Réessayez dans un instant.",
    geo_timeout:
      "Le service de l'IGN a mis trop de temps à répondre. Réessayez.",
    bbox_too_large: "Zoomez davantage pour afficher les parkings.",
    invalid_geometry: "Forme invalide.",
    too_many_vertices: "Forme trop détaillée (trop de sommets).",
    too_many_items: "Trop d'éléments.",
    invalid_item: "Élément invalide.",
    scale_range: "Échelle entre × 0,5 et × 2.",
    password_mismatch: "Les deux mots de passe ne sont pas identiques.",
    terms_required: "Acceptez les conditions pour continuer.",
    invalid_link: "Ce lien n'est plus valable : il a expiré ou a déjà servi.",
    account_suspended: `Ce compte est suspendu. Contactez l'équipe ${PRODUCT.name}.`,
    view_as_read_only:
      "En consultation, l'équipe, les mots de passe et les paiements du loueur ne se modifient pas.",
    view_as_ended: "La consultation de l'espace du loueur est terminée.",
    email_not_verified:
      "Confirmez d'abord votre adresse email (lien reçu par email).",
    listing_required: "Enregistrez d'abord votre fiche.",
    commission_range: "Entre 0 et 50 %.",
    cannot_suspend_platform:
      "Le compte de la plateforme ne peut pas être suspendu.",
    no_pending_invitation: "Aucune invitation en attente pour ce loueur.",
    payout_not_failed: "Ce reversement n'est pas en échec.",
    operator_account_not_ready:
      "Le compte Stripe du loueur ne peut pas encore recevoir de virement.",
    payments_disabled: "Le paiement en ligne n'est pas activé.",
    payments_not_connected: "Activez d'abord les paiements en ligne.",
    payments_unavailable: "Stripe ne répond pas. Réessayez dans un instant.",
    invalid_payout_schedule: "Calendrier de reversement inconnu.",
    invalid_date: "Date invalide.",
    invalid_sms_mode: "Choix inconnu.",
    sms_not_configured: "Choisissez d'abord comment envoyer vos SMS.",
    sms_encryption_key_missing: `Le serveur ${PRODUCT.name} n'a pas sa clé de chiffrement des mots de passe : contactez l'équipe ${PRODUCT.name}.`,
    sms_encryption_key_invalid: `La clé de chiffrement du serveur ${PRODUCT.name} est invalide : contactez l'équipe ${PRODUCT.name}.`,
    sms_password_unreadable:
      "Le mot de passe enregistré ne peut plus être lu : saisissez-le à nouveau.",
    brevo_unavailable: `${PRODUCT.name} ne peut pas envoyer de SMS pour le moment : choisissez le téléphone du parking.`,
    sms_gateway_unauthorized:
      "Identifiant ou mot de passe refusé par l'appli : recopiez ceux affichés dans « Cloud server ».",
    sms_gateway_unreachable:
      "Le serveur de l'appli ne répond pas. Réessayez dans un instant.",
    sms_gateway_offline:
      "Le téléphone du parking est hors ligne : ouvrez l'appli et vérifiez qu'elle est « Online ».",
    sms_gateway_rejected: "L'appli a refusé le SMS (numéro ou texte invalide).",
    sms_gateway_error: "L'appli SMS a renvoyé une erreur. Réessayez.",
    sms_gateway_failed:
      "Le téléphone n'a pas pu envoyer le SMS (réseau ou forfait).",
    booking_refunded: "Réservation remboursée : elle ne peut plus être rouverte.",
    refund_failed: "Le remboursement a échoué. Réessayez.",
    spot_not_found: "Place introuvable.",
    spot_inactive: "Cette place est désactivée.",
    not_placeable: "Cette réservation ne peut pas être placée.",
    duplicate_code: "Code de place déjà utilisé.",
    no_spots: "Aucune place ne tient sur ce terrain : agrandissez-le ou vérifiez le tracé.",
    not_site_booking: `Seules les réservations ${PRODUCT.name} ont un lien de gestion.`,
    invalid_code: "Code de place invalide.",
    invalid_kind: "Type invalide.",
    boolean: "Oui ou non attendu.",
    invalid_stay_class: "Zone de séjour invalide.",
    invalid_layout: "Disposition invalide.",
    invalid_key_hook: "Crochet : 12 caractères max, lettres, chiffres, espace ou tiret.",
    invalid_airport: "Code aéroport invalide (3 lettres).",
    invalid: "Valeur invalide.",
    invalid_coordinate: "Coordonnées invalides.",
    invalid_bbox: "Zone invalide.",
    too_short: "Saisissez au moins 3 caractères.",
  } as Record<string, string>,
  login: {
    title: "Connexion",
    subtitle: "Espace professionnel",
    welcome: "Bienvenue",
    intro: "Connectez-vous avec le compte de votre parking.",
    email: "Email",
    password: "Mot de passe",
    submit: "Se connecter",
    passwordChanged: "Mot de passe modifié. Reconnectez-vous.",
    noAccount: "Pas encore de compte ?",
    signup: "Inscrire mon parking",
  },
  signup: {
    title: "Inscrire mon parking",
    subtitle: (product: string) =>
      `Rejoignez ${product} : votre fiche est vérifiée par notre équipe avant d'être en ligne.`,
    company: "Entreprise",
    parkingName: "Nom du parking",
    capacity: "Capacité (places)",
    airport: "Aéroport",
    chooseAirport: "Choisir un aéroport",
    managerName: "Prénom et nom",
    email: "Email",
    phone: "Téléphone",
    password: "Mot de passe",
    passwordHelp: "Au moins 10 caractères.",
    passwordConfirmation: "Confirmer le mot de passe",
    terms:
      "J'accepte les conditions d'utilisation de l'espace professionnel et le traitement de ces données pour gérer mon compte.",
    termsLink: "Lire les conditions",
    privacy:
      "Nous ne gardons que ce qui sert à votre compte : votre nom, votre email et votre téléphone.",
    submit: "Créer mon compte",
    submitting: "Création du compte…",
    hasAccount: "Déjà un compte ?",
    login: "Se connecter",
    honeypot: "Ne pas remplir ce champ",
    // The account may already exist: the API answers the same, the login then fails.
    checkInbox:
      "Si cette adresse n'avait pas encore de compte, il vient d'être créé. Sinon, un email vous a été envoyé : connectez-vous avec votre mot de passe habituel.",
  },
  onboarding: {
    title: "Bienvenue ! Votre compte est créé.",
    steps: [
      "Remplissez votre fiche et vos tarifs.",
      "Envoyez-la pour validation : notre équipe la vérifie avant sa mise en ligne.",
    ],
  },
  emailBanner: {
    text: "Confirmez votre adresse email : nous vous avons envoyé un lien. Il faut l'avoir confirmée pour envoyer votre fiche en validation.",
    resend: "Renvoyer le lien",
    resent: "Nouveau lien envoyé.",
    devLink:
      "Email non configuré (développement) : ouvrir le lien de confirmation",
  },
  verifyEmail: {
    title: "Confirmation de l'adresse email",
    checking: "Vérification du lien…",
    done: "Adresse email confirmée. Vous pouvez envoyer votre fiche en validation.",
    missing: "Lien incomplet : ouvrez le lien reçu par email.",
    toSpace: "Aller à mon espace",
    toLogin: "Se connecter",
  },
  invitation: {
    title: "Choisir mon mot de passe",
    intro: (operator: string, email: string) =>
      `Espace de ${operator} · ${email}`,
    checking: "Vérification de l'invitation…",
    password: "Mot de passe",
    passwordConfirmation: "Confirmer le mot de passe",
    submit: "Accéder à mon espace",
    invalid: `Cette invitation n'est plus valable : elle a expiré ou a déjà servi. Demandez à l'équipe ${PRODUCT.name} de vous la renvoyer.`,
  },
  viewAs: {
    banner: (name: string) => `Vous consultez l'espace de ${name}`,
    note: "Vos modifications sont tracées dans le journal à votre nom.",
    back: "Revenir à la plateforme",
    readOnly:
      "En consultation, l'équipe, les mots de passe et le compte du loueur sont en lecture seule.",
  },
  nav: {
    planning: "Planning",
    shuttles: "Navettes",
    plazo: `Sur ${PRODUCT.name}`,
    reservations: "Réservations",
    dashboard: "Tableau de bord",
    parking: "Parking",
    team: "Équipe",
    account: "Mon compte",
    logout: "Se déconnecter",
    platform: "Plateforme",
  },
  dashboard: {
    hello: (name: string) => `Bonjour ${name}`,
    title: "Tableau de bord",
    today: (date: string) => `Aujourd'hui · ${date}`,
    refreshed: (ago: string) => `Actualisé ${ago}`,
    loadError: "Impossible de charger le tableau de bord.",
    kpi: {
      onSite: "Sur le parking",
      onSiteSub: (free: number | null, planned: number) =>
        free === null ? `${planned === 0 ? "plan à dessiner" : ""}` : `${free} libre${free > 1 ? "s" : ""} sur ${planned}`,
      arrivals: "Arrivées",
      arrivalsSub: (arrived: number, total: number) => `${arrived} / ${total} sur place`,
      returns: "Retours",
      returnsSub: (week: number) => `${week} cette semaine`,
      shuttles: "Navettes",
      shuttlesSub: (n: number) => (n === 0 ? "aucune en route" : n === 1 ? "en route" : "en route"),
      nextWave: (time: string, passengers: number, vehicles: number | null) =>
        `prochaine ${time} · ${passengers} pass.${vehicles && vehicles > 1 ? ` · ${vehicles} navettes` : ""}`,
      toTreat: "À traiter",
      toTreatSub: (urgent: number) => (urgent === 0 ? "rien d'urgent" : `${urgent} urgent${urgent > 1 ? "s" : ""}`),
    },
    services: {
      title: "Services",
      ok: "OK",
      warn: "À voir",
      off: "Off",
      flights: "Vols",
      flightsOn: (provider: string | null) => (provider ? `suivi ${provider}` : "suivi actif"),
      flightsOff: "non configuré",
      sms: "SMS",
      smsOff: "désactivés",
      smsPending: (n: number) => `${n} en attente`,
      smsOk: "prêts",
      smsStale: "en retard",
      push: "Notifications",
      pushOn: (devices: number) => `${devices} appareil${devices > 1 ? "s" : ""}`,
      pushOff: "non configurées",
      stripe: "Paiements",
      stripeOn: "reversements actifs",
      stripePending: "compte à finaliser",
      stripeOff: "non connecté",
      importLabel: "Import",
      importAt: (ago: string) => `dernier ${ago}`,
      importNever: "jamais",
    },
    alerts: {
      title: "À traiter maintenant",
      urgentCount: (n: number) => `${n} urgent${n > 1 ? "s" : ""}`,
      empty: "Rien à traiter : tout est en ordre.",
      since: (minutes: number) => `depuis ${minutes} min`,
      severity: { urgent: "Urgent", watch: "À surveiller", todo: "À faire" },
      kind: {
        no_spot: "Sur place sans place",
        no_free_spot: "Plus de place libre",
        arriving_unplaced: "Arrivée sans place prévue",
        flight_delayed: "Vol retardé",
        flight_cancelled: "Vol annulé",
        waiting_at_meeting_point: "Attend au point de rendez-vous",
        keys_missing: "Clés non accrochées",
        sms_pending: "SMS en attente",
        overbooked: "Surréservation",
        departure_cancelled: "Vol aller annulé",
        departure_delayed: "Vol aller retardé",
        wave_overflow: "Vague au-delà d'une navette",
        no_show_suspected: "Attendu, toujours pas là",
      } satisfies Record<AlertKind, string>,
      waveDetail: (direction: ShuttleDirection, time: string, passengers: number) =>
        `${direction === "dropoff" ? "Vers le terminal" : "Depuis l'aéroport"} ${time} · ${passengers} passagers`,
    },
    vehicles: {
      title: "Véhicules sur le parking",
      count: (n: number) => `${n} véhicule${n > 1 ? "s" : ""}`,
      empty: "Aucun véhicule sur le parking.",
      noSpot: "Sans place",
      keys: (hook: string) => `Clés ${hook}`,
      noKeys: "Clés ?",
      returnToday: (time: string) => `Retour ${time}`,
      returnLater: (day: string) => `Retour ${day}`,
      onTrip: { pickup: "Navette · retour", dropoff: "Navette · terminal" } satisfies Record<ShuttleDirection, string>,
      stay: { short: "zone court", medium: "zone moyen", long: "zone long" } as Record<string, string>,
      all: "Tous les véhicules",
      pax: (n: number) => `${n} pass.`,
      keysHook: (hook: string) => `Clés : crochet ${hook}`,
      flight: (code: string, time: string) => `Vol ${code} · ${time}`,
      badge: {
        returnToday: "Retour du jour",
        landed: "Atterri",
        delayed: (min: number) => `Retardé +${min} min`,
        cancelled: "Vol annulé",
        onTrip: "Sur un trajet",
        shuttled: "Navette faite",
        waiting: "Attend la navette",
        onSite: "Sur place",
        noSpot: "Sans place",
        noKeys: "Clés ?",
      },
    },
    map: {
      title: "Navettes en direct",
      none: "Aucune navette en route.",
      parking: "Parking",
      direction: { pickup: "Retours · aéroport", dropoff: "Départs · terminal" } satisfies Record<ShuttleDirection, string>,
      passengers: (n: number) => `${n} pass.`,
      toStop: (name: string, min: number) => `${name} dans ${min} min`,
      toParking: (min: number) => `parking dans ${min} min`,
      noPosition: "position inconnue",
      open: "Ouvrir les retours",
      shuttle: (n: number) => `Navette ${String(n).padStart(2, "0")}`,
      since: (at: Date) => `partie à ${new Intl.DateTimeFormat("fr-FR", { hour: "2-digit", minute: "2-digit", timeZone: "Europe/Paris" }).format(at)}`,
      legend: { fresh: "position récente", stale: "position ancienne" },
    },
    totalCapacity: "Places au total",
    bookableCapacity: "Places réservables",
    safetyMargin: "Marge de sécurité",
    shuttle: "Trajet navette",
    minutes: (n: number) => `${n} min`,
    places: (n: number) => `${n} place${n > 1 ? "s" : ""}`,
    bookableHelp:
      "Capacité totale moins la marge de sécurité : c'est le plafond utilisé contre la surréservation.",
  },
  parking: {
    tabs: {
      plan: "Plan",
      occupation: "Occupation",
      planning: "Planning des places",
      settings: "Réglages",
    },
    title: "Réglages du parking",
    name: "Nom du parking",
    address: "Adresse",
    totalCapacity: "Nombre de places au total",
    safetyMarginPct: "Marge de sécurité (%)",
    safetyMarginHelp:
      "Part des places jamais proposées à la réservation (imprévus, prolongations).",
    shuttleTravelMinutes: "Durée du trajet navette (minutes)",
    shuttleHelp: "Entre le parking et le terminal.",
    terminalLeadMinutes: "Présence au terminal avant le décollage (minutes)",
    terminalLeadHelp: "La navette aller part ce délai plus le trajet avant le décollage du vol aller.",
    landingDelayMinutes: "Délai après l'atterrissage (minutes)",
    landingDelayHelp: "Bagages, douane : le temps entre l'atterrissage et le point de rendez-vous.",
    bookablePreview: (n: number) =>
      `Places réservables avec ces réglages : ${n}`,
  },
  meetingPoint: {
    title: "Point de rendez-vous au retour",
    intro:
      "Là où la navette récupère vos clients à l'aéroport. Le voyageur y est guidé à pied depuis le terminal, avec vos consignes et votre photo.",
    none: "Aucun point défini : l'aéroport de votre fiche est utilisé.",
    search: "Rechercher une adresse ou un lieu",
    searchPlaceholder: "ex. Aéroport Lyon Saint-Exupéry, Terminal 1",
    searchAction: "Chercher",
    noResult: "Aucun résultat.",
    mapHelp:
      "Cliquez sur la carte (ou déplacez le repère) pour placer le point exact.",
    label: "Libellé",
    labelPlaceholder: "ex. Terminal 1 · Porte 12 · Arrêt navettes parkings",
    instructions: "Consignes pour le voyageur",
    instructionsHelp: (left: number) =>
      `Chemin depuis la sortie bagages, repères, où attendre. ${left} caractères restants.`,
    photoUrl: "Photo du point de rendez-vous (adresse web)",
    photoUrlHelp:
      "Pas encore d'envoi de fichier : collez l'adresse d'une photo en ligne (https://…), comme pour les photos de votre fiche.",
    photoPreview: "Aperçu de la photo du point de rendez-vous",
    coordinates: (lat: number, lng: number) =>
      `Position : ${lat.toFixed(5)}, ${lng.toFixed(5)}`,
    clear: "Supprimer le point",
    saved: "Point de rendez-vous enregistré.",
    cleared: "Point de rendez-vous supprimé.",
    needPoint: "Placez d'abord le point sur la carte.",
  },
  vehicles: {
    title: "Navettes",
    intro:
      "Vos véhicules : le chauffeur choisit le sien au départ d'un trajet, et le voyageur sait quelle navette attendre.",
    empty:
      "Aucune navette enregistrée : le chauffeur saisira son véhicule à la main.",
    model: "Modèle",
    modelPlaceholder: "ex. Mercedes Vito",
    colour: "Couleur",
    colourPlaceholder: "ex. blanche",
    plate: "Plaque",
    seats: "Places passagers",
    seatsHelp: "Hors chauffeur ; limite le nombre de clients d'un trajet.",
    seatsShort: (n: number) => `${n} pl.`,
    driver: "Chauffeur habituel",
    driverNone: "Aucun (au choix du chauffeur)",
    inService: "En service",
    outOfService: "Hors service",
    outOfServiceHelp: "Un véhicule hors service n'est pas proposé au départ d'un trajet.",
    add: "Ajouter la navette",
    edit: "Modifier",
    editLabel: (model: string) => `Modifier la navette ${model}`,
    editing: (model: string) => `Modification de ${model}`,
    save: "Enregistrer",
    cancel: "Annuler",
    remove: "Retirer",
    removeLabel: (model: string) => `Retirer la navette ${model}`,
    added: "Navette ajoutée.",
    updated: "Navette modifiée.",
    removed: "Navette retirée.",
  },
  stops: {
    title: "Dessertes de la navette",
    intro:
      "Les lieux desservis en plus de l'aéroport (gare TGV, hôtel…). Le chauffeur choisit la desserte au départ d'un trajet ; une réservation peut en indiquer une.",
    airport: "Aéroport",
    airportHelp: "Toujours desservi : le point de rendez-vous ci-dessus.",
    airportUnset: "Aéroport : point de rendez-vous à définir ci-dessus.",
    empty: "Aucune autre desserte : la navette ne va qu'à l'aéroport.",
    kind: "Type",
    kinds: { airport: "Aéroport", station: "Gare", other: "Autre lieu" } as Record<ShuttleStopKind, string>,
    name: "Nom",
    namePlaceholder: "ex. Gare Saint-Exupéry TGV",
    search: "Adresse ou lieu",
    searchPlaceholder: "ex. Gare Lyon Saint-Exupéry",
    searchAction: "Chercher",
    noResult: "Aucun lieu trouvé.",
    coordinates: (lat: number, lng: number) => `${lat.toFixed(5)}, ${lng.toFixed(5)}`,
    needPoint: "Cherchez d'abord le lieu pour le placer.",
    instructions: "Consignes pour le voyageur (facultatif)",
    instructionsHelp: (left: number) => `${left} caractères restants.`,
    add: "Ajouter la desserte",
    edit: "Modifier",
    editLabel: (name: string) => `Modifier la desserte ${name}`,
    editing: (name: string) => `Modification de ${name}`,
    save: "Enregistrer",
    cancel: "Annuler",
    remove: "Retirer",
    removeLabel: (name: string) => `Retirer la desserte ${name}`,
    added: "Desserte ajoutée.",
    updated: "Desserte modifiée.",
    removed: "Desserte retirée.",
  },
  team: {
    title: "Équipe",
    postToday: "Poste du jour",
    vehicleToday: "Véhicule du jour",
    postSince: (when: string) => `depuis ${when}`,
    add: "Ajouter un membre",
    name: "Nom",
    email: "Email",
    phone: "Téléphone",
    role: "Rôle",
    active: "Actif",
    inactive: "Désactivé",
    lastLogin: "Dernière connexion",
    password: "Mot de passe provisoire",
    passwordHelp:
      "À communiquer à la personne, qui le changera dans « Mon compte ».",
    create: "Créer le compte",
    created: "Compte créé",
    updated: "Membre mis à jour",
    deactivate: "Désactiver",
    reactivate: "Réactiver",
    resetPassword: "Nouveau mot de passe",
    passwordReset: "Mot de passe réinitialisé. Ses sessions ont été fermées.",
    you: "vous",
  },
  account: {
    title: "Mon compte",
    currentPassword: "Mot de passe actuel",
    newPassword: "Nouveau mot de passe",
    submit: "Changer le mot de passe",
  },
  status: {
    upcoming: "Attendu",
    arrived: "Sur place",
    shuttled_out: "Parti en navette",
    return_requested: "Retour demandé",
    back_at_parking: "De retour au parking",
    returned: "Rendu",
    cancelled: "Annulé",
    no_show: "Non venu",
  } satisfies Record<ReservationStatus, string>,
  statusAction: {
    upcoming: "Remettre en attente",
    arrived: "Enregistrer l'arrivée",
    shuttled_out: "Parti en navette",
    return_requested: "Client au point de rendez-vous",
    back_at_parking: "Client de retour au parking",
    returned: "Véhicule rendu",
    cancelled: "Annuler la réservation",
    no_show: "Marquer non venu",
  } satisfies Record<ReservationStatus, string>,
  channels: {
    website: "Site",
    phone: "Téléphone",
    counter: "Comptoir",
    aggregator: "Comparateur",
    import: "Import",
    // Booked by a traveller on the public site.
    plazo: PRODUCT.name,
  } satisfies Record<ReservationChannel, string>,
  planning: {
    today: "Aujourd'hui",
    previousDay: "Jour précédent",
    nextDay: "Jour suivant",
    newReservation: "+ Réservation",
    nightsTitle: "Occupation des nuits",
    overbookedBy: (n: number) => `Surréservé +${n}`,
    almostFull: "Presque plein",
    free: (n: number) => `${n} libre${n > 1 ? "s" : ""}`,
    arrivals: "Arrivées",
    returns: "Retours",
    arrivalsCount: (total: number, here: number) =>
      `${total} · ${here} sur place`,
    noArrival: "Aucune arrivée ce jour.",
    noReturn: "Aucun retour ce jour.",
    pax: (n: number) => `${n} pers.`,
    from: (city: string) => `de ${city}`,
    // Travellers telling the parking they are coming (live position or announce).
    approaching: (eta: number | null) =>
      eta === null ? "En route" : `En approche · ${eta} min`,
    announced: (minutes: number) => `Prévenu · « dans ${minutes} min »`,
    atReception: "À l'accueil",
    atMeetingPoint: "Au point de rendez-vous",
    positionUpdated: (seconds: number) =>
      seconds < 60
        ? `Position mise à jour il y a ${seconds} s`
        : `Position mise à jour il y a ${Math.floor(seconds / 60)} min`,
    etaAround: (time: string) => `arrivée estimée ${time}`,
    distance: (meters: number) =>
      meters < 1000
        ? `${meters} m`
        : `${(meters / 1000).toFixed(1).replace(".", ",")} km`,
    miniMap: (name: string) =>
      `Position de ${name} par rapport au point de rendez-vous`,
    meetingPointMark: "P",
    toastApproaching: (who: string, eta: number | null, plate: string) =>
      eta === null
        ? `${who} est en route — ${plate}`
        : `${who} arrive dans ${eta} min — ${plate}`,
    toastAnnounced: (who: string, minutes: number, plate: string) =>
      `${who} : « J'arrive dans ${minutes} min » — ${plate}`,
    toastAtReception: (who: string, plate: string) =>
      `${who} est à l'accueil — ${plate}`,
    toastAtMeetingPoint: (who: string, plate: string) =>
      `Retour : ${who} est au point de rendez-vous — ${plate}`,
    toastSee: "Voir ›",
    toastClose: "Fermer l'alerte",
    // The driver's trip picking this traveller up (position shared with them).
    shuttleOnTheWay: (driver: string) => `Navette en route (${driver})`,
    smsWarning: (n: number) => `${n} SMS en attente · téléphone injoignable`,
    smsWarningHint:
      "Allumez le téléphone du parking et ouvrez l'appli SMS Gateway. Les SMS en attente plus de 2 h sont abandonnés.",
  },
  reservation: {
    pricePaid: "Prix payé",
    newTitle: "Nouvelle réservation",
    editTitle: "Modifier la réservation",
    arrival: "Arrivée",
    return: "Retour",
    date: "Date",
    time: "Heure",
    customerName: "Client",
    customerPhone: "Téléphone",
    customerEmail: "Email (facultatif)",
    email: "Email",
    plate: "Plaque",
    returnFlight: "Vol retour",
    returnFlightHelp: "Pour suivre l'atterrissage et prévoir la navette retour.",
    departureFlight: "Vol aller (facultatif)",
    departureFlightHelp: "Pour prévoir la navette vers le terminal avant le décollage.",
    departureStatus: {
      scheduled: "à l'heure",
      delayed: "retardé",
      departed: "parti",
      landed: "parti",
      cancelled: "annulé",
      diverted: "dérouté",
      unknown: "vol inconnu",
    } as Record<string, string>,
    takeOff: (time: string) => `décollage ${time}`,
    carPosition: "Position de la voiture",
    carBy: { traveller: "donnée par le client", staff: "prise par l'équipe" } as Record<string, string>,
    carAccuracy: (m: number) => `± ${m} m`,
    carDirections: "Itinéraire à pied",
    stop: "Desserte",
    stopAirport: "Aéroport",
    passengers: "Passagers",
    channel: "Canal",
    channelDetail: "Nom du comparateur",
    notes: "Notes",
    nights: (n: number) => `${n} nuit${n > 1 ? "s" : ""}`,
    save: "Enregistrer",
    saved: "Réservation enregistrée",
    full: (days: string) => `Complet : ${days}.`,
    fullHelp:
      "Refusée sur la page publique. Au comptoir, vous pouvez l'enregistrer quand même en connaissance de cause.",
    fullNoForce: "Seul un agent ou le gérant peut l'enregistrer quand même.",
    force: "Enregistrer quand même (surréservation)",
    available: (n: number) =>
      `Disponible : au moins ${n} place${n > 1 ? "s" : ""} libre${n > 1 ? "s" : ""} chaque nuit.`,
    reference: "Référence",
    overbookedBadge: "Surréservation",
    edit: "Modifier",
    cancelEdit: "Annuler la modification",
    status: "Statut",
    journey: "Étapes",
    contact: "Contact",
    stay: "Séjour",
    created: "Créée le",
    searchPlaceholder: "Plaque, nom, téléphone ou référence",
    search: "Rechercher",
    noResult: "Aucune réservation trouvée.",
    previous: "Précédent",
    next: "Suivant",
    page: (p: number, total: number) => `Page ${p} / ${total}`,
    listTitle: "Réservations",
    back: "Retour",
  },
  payments: {
    kicker: "Paiements en ligne · à activer",
    title: `Recevez l'argent des réservations ${PRODUCT.name} sur votre compte bancaire`,
    intro: {
      before: `Les voyageurs paient par carte sur ${PRODUCT.name}. ${PRODUCT.name} garde sa commission (`,
      after:
        ") et vous reverse le reste automatiquement. Tant que ce n'est pas activé, votre fiche affiche « Réservation en ligne bientôt disponible ».",
    },
    commissionUnset: "à définir",
    steps: [
      "1. Vos informations et votre IBAN chez Stripe",
      "2. Vérification (quelques minutes à 2 jours)",
      "3. Réservations ouvertes",
    ],
    activate: "Activer les paiements ›",
    redirectNote:
      "Vous serez redirigé vers Stripe, notre prestataire de paiement.",
    testModeNote: "Mode test : aucun argent réel.",
    pendingKicker: "Paiements en ligne · vérification",
    pendingTitle: "Vérification en cours chez Stripe",
    pendingText:
      "Stripe vérifie vos informations, en général de quelques minutes à 2 jours. Vos réservations en ligne s'ouvrent dès que c'est fait. Si Stripe demande un document, complétez votre dossier.",
    complete: "Compléter mon dossier ›",
    active: "Paiements en ligne : actifs",
    manage: "Gérer sur Stripe ›",
    disabled: `Paiements en ligne : pas encore ouverts sur ${PRODUCT.name}. Les voyageurs réservent et paient au parking.`,
    readOnly:
      "Consultation : seul le loueur peut activer ses paiements et choisir quand recevoir son argent.",
    returned: "Dossier envoyé à Stripe",
    expired: "Lien expiré, recommencez",
    scheduleTitle: "Quand recevoir votre argent ?",
    scheduleSaved: "Calendrier de reversement enregistré",
    scheduleFootnote: `${PRODUCT.name} encaisse le paiement du voyageur, garde sa commission et vous vire le reste à la date choisie. Stripe verse ensuite sur votre IBAN sous 2 à 7 jours.`,
    recommended: "conseillé",
    schedule: {
      AT_DROP_OFF: {
        title: "Au dépôt",
        text: "le lendemain de l'arrivée du véhicule",
      },
      AFTER_STAY: { title: "Fin du séjour", text: "le lendemain du retour" },
      WEEKLY: { title: "Chaque semaine", text: "le lundi, séjours terminés" },
      MONTHLY: { title: "Chaque mois", text: "le 1er, séjours terminés" },
    } satisfies Record<PayoutSchedule, { title: string; text: string }>,
  },
  sms: {
    title: "SMS aux voyageurs",
    kickerSetup: "Envoi des SMS · à configurer",
    kickerGateway: "Envoi des SMS · téléphone du parking",
    kickerBrevo: `Envoi des SMS · ${PRODUCT.name} envoie pour vous`,
    kickerNone: "Envoi des SMS · désactivé",
    headline:
      "Envoyez les SMS depuis le téléphone de votre parking, gratuitement",
    intro:
      "Confirmation, rappel du point de rendez-vous à l'atterrissage, navette en approche : les SMS partent de votre propre numéro, avec votre forfait. Les voyageurs peuvent y répondre ou vous rappeler.",
    modes: {
      gateway: {
        title: "Téléphone du parking",
        text: "Gratuit · un Android allumé avec SMS illimités",
      },
      brevo: {
        title: `${PRODUCT.name} envoie pour moi`,
        text: "0,05 € par SMS, décompté sur vos reversements",
      },
      none: { title: "Pas de SMS", text: "Email seulement" },
    } satisfies Record<SmsMode, { title: string; text: string }>,
    steps: [
      {
        before:
          "Sur le téléphone Android du parking, installez l'appli gratuite ",
        strong: "SMS Gateway for Android",
        after: " (Play Store ou GitHub).",
      },
      {
        before: "Ouvrez-la, choisissez ",
        strong: "« Cloud server »",
        after:
          " et activez-la : elle affiche un identifiant et un mot de passe.",
      },
      {
        before: "Recopiez-les ici, puis envoyez un SMS de test.",
        strong: "",
        after: "",
      },
    ],
    login: "Identifiant affiché par l'appli",
    loginPlaceholder: "ex. AB12CD",
    password: "Mot de passe affiché par l'appli",
    passwordKept: "Laissez vide pour garder celui enregistré.",
    senderPhone: "Numéro du téléphone (expéditeur)",
    testRecipient: "Envoyer un SMS de test à",
    phonePlaceholder: "+33 6 …",
    advanced: "Serveur (avancé)",
    advancedHelp:
      "Vide : le serveur public de l'appli. Sinon l'adresse https:// de votre serveur privé.",
    link: "Relier et tester",
    linking: "Liaison…",
    noAndroid: "Je n'ai pas de téléphone Android",
    chooseOther: "Choisir",
    saved: "Réglage enregistré",
    linked: "Téléphone relié",
    testSent: (to: string) =>
      `SMS de test envoyé à ${to} : vérifiez sa réception.`,
    testQueued: (to: string) =>
      `SMS de test transmis au téléphone pour ${to} : il part dès que le téléphone est en ligne.`,
    testFailed: "Le SMS de test n'est pas parti.",
    linkedStatus: "Relié",
    lastSent: (ago: string) => `dernier SMS envoyé ${ago}`,
    neverSent: "aucun SMS envoyé pour l'instant",
    sender: "Expéditeur",
    monthSent: (n: number) => `${n} SMS envoyé${n > 1 ? "s" : ""} ce mois`,
    monthFailed: (n: number) => `${n} échec${n > 1 ? "s" : ""}`,
    pending: (n: number) => `${n} en attente`,
    pendingStale: "téléphone injoignable",
    sendTest: "Envoyer un SMS de test",
    sendTestTo: "Numéro qui recevra le SMS de test",
    send: "Envoyer",
    cancel: "Annuler",
    edit: "Modifier",
    disable: "Désactiver",
    disableConfirm:
      "Désactiver les SMS ? Les voyageurs ne recevront plus que les emails.",
    disabled: "SMS désactivés",
    offlineWarning:
      "Si le téléphone est éteint ou hors ligne, les SMS sont mis en attente 2 h puis abandonnés ; le planning le signale.",
    lastError: (ago: string) => `Dernière erreur ${ago} :`,
    brevoActive: `${PRODUCT.name} envoie vos SMS depuis son propre numéro, 0,05 € par SMS décomptés sur vos reversements.`,
    noneActive: `${PRODUCT.name} n'envoie pas de SMS pour votre parking : les voyageurs reçoivent les emails seulement.`,
    changeChannel: "Changer",
    footnote: `Tant que rien n'est configuré, ${PRODUCT.name} n'envoie pas de SMS pour votre parking (les emails partent quand même). Le mot de passe est chiffré côté serveur et jamais réaffiché.`,
    readOnly:
      "Consultation : seul le loueur peut relier son téléphone ou changer l'envoi des SMS.",
  },
  listingStatus: {
    draft: "Brouillon",
    pending_review: "À valider",
    published: "Publiée",
    rejected: "Refusée",
  } satisfies Record<ListingStatus, string>,
  plazo: {
    tabs: { listing: "Ma fiche", pricing: "Mes tarifs" },
    submit: "Envoyer pour validation",
    submitted:
      "Fiche envoyée : notre équipe la vérifie avant sa mise en ligne.",
    withdraw: `Retirer de ${PRODUCT.name}`,
    cancelRequest: "Annuler la demande",
    withdrawn: "Votre fiche n'est plus en ligne.",
    requestCancelled: "Demande de validation annulée.",
    statusHelp: {
      draft:
        "Votre fiche n'est pas visible. Remplissez-la, enregistrez vos tarifs, puis envoyez-la pour validation.",
      pending_review:
        "Notre équipe vérifie votre fiche. Vous pouvez encore la modifier.",
      published:
        "Votre fiche est en ligne. Vos modifications s'appliquent tout de suite.",
      rejected:
        "Votre fiche est à corriger. Corrigez-la, puis envoyez-la à nouveau.",
    } satisfies Record<ListingStatus, string>,
    reviewMessage: `Message de l'équipe ${PRODUCT.name}`,
    verifyFirst: "Confirmez votre email pour pouvoir envoyer votre fiche.",
    saved: "Fiche enregistrée",
    airport: "Aéroport",
    title: "Nom affiché",
    slug: "Adresse de la page",
    description: "Présentation",
    services: "Services",
    shuttleMinutes: "Navette (min)",
    distanceKm: "Distance (km)",
    openingHours: "Horaires",
    openingHoursPlaceholder: "24h/24",
    cancellation: "Annulation",
    photos: "Photos (la première sert de vignette)",
    photoUrl: "Adresse de la photo (https://…)",
    addPhoto: "+ Photo",
    removePhoto: "Retirer la photo",
    photosHelp:
      "Collez l'adresse d'une photo en ligne. L'envoi de fichiers depuis l'ordinateur arrive bientôt.",
    preview: `Aperçu dans les résultats ${PRODUCT.name}`,
    from: (price: string) => `dès ${price}`,
    noPrice: "prix à définir",
    newOnPlazo: `Nouveau sur ${PRODUCT.name}`,
    see: "Voir",
    viewPage: "Voir ma page",
    save: "Enregistrer",
    pricingIntro:
      "Un séjour paie le forfait le moins cher qui le couvre. Les jours se comptent du jour d'arrivée au jour de retour inclus.",
    duration: "Durée",
    priceAll: "Prix tout compris",
    upTo: "Jusqu'à",
    dayUnit: (n: number) => (n > 1 ? "jours" : "jour"),
    removeTier: "Supprimer ce forfait",
    addTier: "+ Ajouter un forfait",
    extraDay: (days: number) =>
      `Au-delà de ${days} jour${days > 1 ? "s" : ""}, chaque jour en plus :`,
    extraDayNoTier: "Chaque jour au-delà du plus long forfait :",
    extraDayLabel: "Prix du jour supplémentaire",
    savePricing: "Enregistrer les tarifs",
    pricingSaved: "Tarifs enregistrés",
    unsaved: "Modifié · non enregistré",
    simulationTitle: "Ce que paie le voyageur",
    simDays: (n: number) => `${n} j`,
    simTier: (n: number) => `Forfait ${n} jour${n > 1 ? "s" : ""}`,
    simExtra: (base: number, extra: number, price: string) =>
      `${base} jours + ${extra} × ${price}`,
    simNone: "Pas de prix : ajoutez un forfait plus long ou un prix par jour",
    commission: (pct: string) =>
      `Sur une réservation payée en ligne, ${PRODUCT.name} retient sa commission (${pct} %) et vous reverse le reste. Les réservations au comptoir, par téléphone ou via les comparateurs ne sont pas concernées.`,
    commissionUnset:
      `Sur une réservation payée en ligne, ${PRODUCT.name} retient une commission (taux à convenir) et vous reverse le reste. Les réservations au comptoir, par téléphone ou via les comparateurs ne sont pas concernées.`,
    invalidPrice: "Prix invalide (ex. 34,99).",
    invalidDays: "Entre 1 et 90 jours.",
  },
  services: {
    shuttle: "Navette",
    open_24h: "24h/24",
    fenced: "Clôturé",
    cctv: "Vidéosurveillance",
    valet: "Voiturier",
    covered: "Couvert",
    ev_charging: "Recharge électrique",
  } satisfies Record<ListingService, string>,
  cancellation: {
    free_24h: ["Gratuite 24 h avant", "remboursement total"],
    free_48h: ["Gratuite 48 h avant", "remboursement total"],
    free_until_arrival: ["Jusqu'à l'arrivée", "remboursement total"],
    non_refundable: ["Non remboursable", ""],
  } satisfies Record<CancellationPolicy, [string, string]>,
  cancellationShort: {
    free_24h: "Annulation gratuite 24 h",
    free_48h: "Annulation gratuite 48 h",
    free_until_arrival: "Annulation gratuite",
    non_refundable: "Non remboursable",
  } satisfies Record<CancellationPolicy, string>,
  capacity: {
    steps: ["Repérer le terrain", "Découper en zones", "Estimer la capacité"],
    study: "Étude",
    rename: "Renommer l'étude",
    saving: "Enregistrement…",
    saved: "Enregistré",
    saveError: "Non enregistré",
    // Study list
    listTitle: "Mes études",
    listSubtitle:
      "Estimations de capacité des terrains des loueurs (outil réservé à la plateforme).",
    newStudy: "Nouvelle étude",
    newStudyName: "Nouvelle étude",
    empty: "Aucune étude pour l'instant.",
    colName: "Étude",
    colParcels: "Parcelles",
    colRange: "Fourchette",
    colUpdated: "Mise à jour",
    open: "Ouvrir",
    delete: "Supprimer",
    confirmDelete: (name: string) => `Supprimer l'étude « ${name} » ?`,
    deleted: "Étude supprimée",
    rangeShort: (a: number, b: number) => `${a} à ${b} voitures`,
    // Step 1
    tools: {
      pan: "Déplacer",
      addVertex: "Sommet +",
      removeVertex: "Sommet −",
      cut: "Exclure une partie",
      draw: "Dessiner",
    },
    toolHelp: {
      pan: "Cliquez sur le terrain pour ajouter ou retirer sa parcelle cadastrale.",
      addVertex:
        "Faites glisser un sommet, ou un point milieu pour en ajouter un.",
      removeVertex: "Cliquez sur un sommet pour le retirer.",
      cut: "Dessinez la partie à retirer du contour ; double-cliquez pour terminer.",
      draw: "Cliquez chaque coin du terrain ; double-cliquez pour terminer.",
      dimension:
        "Cliquez deux sommets du contour, puis saisissez la distance mesurée sur place.",
    },
    address: "Adresse ou point sur la carte",
    addressPlaceholder: "Adresse, commune ou « latitude, longitude »",
    pointLabel: (lat: number, lon: number) =>
      `Point ${lat.toFixed(5)}, ${lon.toFixed(5)}`,
    searching: "Recherche…",
    noResult: "Aucune adresse trouvée.",
    outline: "Contour proposé",
    noOutline: "Pas encore de contour",
    noOutlineHelp:
      "Cliquez sur le terrain : sa parcelle cadastrale est proposée comme contour. Cliquez les parcelles voisines pour les ajouter.",
    drawByHand: "ou dessiner le contour à la main",
    parcelsLabel: (ids: string) => `Parcelles cadastrales ${ids}`,
    clippedWithParking:
      "recoupées avec la surface de parking repérée par l'IGN (BD TOPO)",
    editedByHand: "contour corrigé à la main",
    drawnByHand: "Contour dessiné à la main",
    clipToParking: "Recouper avec le parking BD TOPO",
    parcelLoading: "Recherche de la parcelle…",
    parcelNone: "Aucune parcelle cadastrale à cet endroit.",
    sources: "Sources affichées",
    sourcePhoto: "Photo aérienne IGN",
    sourcePhotoHelp: (date: string) => `20 cm · ${date} · licence ouverte`,
    sourceParcels: "Parcelles cadastrales",
    sourceParcelsHelp: "API Carto · cadastre",
    sourceParkings: "Parkings BD TOPO",
    sourceParkingsHelp: "IGN · surfaces de parking",
    parkingsZoom: "zoomez pour les afficher",
    help: "Corrigez le contour à la souris (déplacer un sommet, en ajouter, en retirer), puis saisissez une cote mesurée sur place pour caler l'échelle.",
    addDimension: "Ajouter une cote",
    validateOutline: "Valider le contour",
    dimension: "Cote mesurée",
    dimensionPick: (n: number) =>
      n === 0 ? "Cliquez le premier sommet." : "Cliquez le second sommet.",
    dimensionOnMap: (m: string) => `Sur la photo : ${m} m`,
    dimensionMeasured: "Distance mesurée sur place (m)",
    apply: "Appliquer",
    cancel: "Annuler",
    scale: "Échelle",
    scaleNone: "× 1 (aucune cote saisie)",
    scaleValue: (factor: string, measured: string) =>
      `× ${factor} · cote de ${measured} m mesurée sur place`,
    removeScale: "Retirer la cote",
    // Step 2
    zonesTitle: (area: string) => `Zones du terrain · ${area} m²`,
    zoneName: (letter: string) => `Zone ${letter}`,
    zoneSubtitle: "stationnement",
    zoneDetail: "voitures légères",
    addZone: "+ Zone de stationnement",
    addExclusion: "+ Partie exclue (bâtiment, arbre, poteau)",
    chooseExclusion: "Quelle partie exclure ?",
    exclusionKinds: {
      building: "Bâtiment",
      reception: "Accueil et remise des clés",
      shuttle_lane: "Voie navette",
      tree: "Arbre",
      post: "Poteau",
      other: "Autre partie",
    },
    exclusionSubtitle: {
      building: "exclu du stationnement",
      reception: "exclue du stationnement",
      shuttle_lane: "circulation, exclue",
      tree: "dégagement autour du tronc",
      post: "dégagement autour",
      other: "exclue du stationnement",
    },
    laneWidth: "Largeur (m)",
    clearance: "Dégagement (m)",
    drawZoneHelp:
      "Dessinez la zone sur la carte ; double-cliquez pour terminer.",
    drawLineHelp: "Tracez l'axe de la voie ; double-cliquez pour terminer.",
    drawPointHelp: "Cliquez l'emplacement sur la carte.",
    editHelp: "Faites glisser les sommets de l'élément sélectionné.",
    remove: "Retirer",
    back: "Retour",
    estimate: "Estimer la capacité",
    noZone: "Ajoutez au moins une zone de stationnement.",
    // Step 3
    compared: (zone: string, area: string) =>
      `${zone} · ${area} m² · 3 dispositions comparées`,
    zonesCount: (n: number) => `${n} zones`,
    computing: "Calcul des dispositions…",
    layouts: {
      selfPark: "Clients garés seuls",
      valet24: "Voiturier · files de 2 à 4",
      valet5: "Voiturier · files de 5",
      valetEdge: "Voiturier · files depuis le bord",
    },
    cars: "voitures",
    perCar: (m2: string) => `${m2} m² par voiture`,
    selfParkDetail: (slot: string, aisle: string, endStalls: boolean) =>
      `Épi 90°, places ${slot} m, allées ${aisle} m${endStalls ? ", places en bout d'allée" : ""}`,
    valet24Detail: (pattern: string, depth: number) =>
      `Blocs ${pattern}, aucune voiture à plus de ${depth} rangs d'une allée`,
    valet5Detail: (pattern: string) =>
      `Blocs ${pattern} : plus dense, mais fragile en cas de retour avancé`,
    valetEdgeDetail: (deepest: number) =>
      `Une allée le long du bord, files jusqu'à ${deepest} voitures ; les coins sont remplis, aucune allée intérieure`,
    aisle: "allée",
    range: (a: number, b: number) => `${a} à ${b} voitures`,
    rangeLabel: "Fourchette à annoncer : ",
    ceiling: (n: number) => `Plafond théorique sans aucune allée : ${n}.`,
    photoCheck: "Contrôle sur la photo : ",
    photoCounted: (n: number) => `≈ ${n} voitures comptées`,
    photoOn: (date: string) => ` le ${date} (comptage à la main).`,
    photoTodo: "compter les voitures sur la photo",
    settings: "Réglages",
    overlaySlot: "Place",
    overlayAisle: "Allée",
    overlayOrientation: "Orientation",
    overlayDepth: "Profondeur max",
    auto: "auto",
    selfParkSlot: "Place client (largeur × longueur, m)",
    valetSlot: "Place voiturier (largeur × longueur, m)",
    aisleWidth: "Largeur d'allée (m)",
    maxDepth: "Profondeur max entre deux allées",
    setback: "Retrait en bordure (m)",
    orientation: "Orientation (°, vide = auto)",
    endStalls: "Places en bout d'allée (clients)",
    crossAisles: "Allées transversales aux extrémités",
    export: "Exporter (GeoJSON)",
    createPlan: "Créer le plan du parking",
    soon: "Bientôt (jalon 4)",
    noResult3: "Aucune place ne tient : vérifiez les zones et les réglages.",
    // Photo check
    photoTitle: "Contrôle sur la photo",
    photoHelp: (date: string) =>
      `voitures comptées sur la photo IGN du ${date} (cliquez sur chaque voiture ; cliquez à nouveau pour la retirer)`,
    occupied: (area: string) => `Surface occupée : ${area} m²`,
    observed: "Constaté : ",
    perCarSuffix: " par voiture",
    estimated: "Estimé (voiturier 2–4) : ",
    photoNote:
      "La photo date de juillet 2023, un jour quelconque : elle montre un remplissage, pas une capacité maximale. À comparer avec le pic réel donné par le gérant.",
    clearCount: "Effacer le comptage",
    save: "Enregistrer",
    backToEstimate: "Retour à l'estimation",
  },
  // Bloc 2, step "Planning des places" (P-A, 04/10/2026): one line per spot over the coming days.
  spotPlanning: {
    title: "Planning des places",
    intro:
      "Une ligne par place : qui l'occupe, qui est attendu, et les jours où il manquera des places.",
    noPlan: "Générez d'abord les places dans le volet Plan.",
    today: "Aujourd'hui",
    prev: "Semaine précédente",
    next: "Semaine suivante",
    windowLabel: "Fenêtre",
    window: (days: number) => `${days} jours`,
    load: "Besoin / places",
    legend: {
      onSite: "Sur place",
      upcoming: "Attendu",
      leaving: "Départ aujourd'hui",
    },
    alerts: "Alertes",
    noAlert: "Rien à signaler sur la fenêtre.",
    overCapacity: (date: string, n: number) =>
      `${date} : ${n} véhicule${n > 1 ? "s" : ""} de trop pour les places`,
    unplacedAlert: (n: number) =>
      `${n} réservation${n > 1 ? "s" : ""} sans place`,
    inactiveUsed: (code: string, ref: string) =>
      `${code} est désactivée mais tient ${ref}`,
    unplaced: (n: number) => `Sans place · ${n}`,
    allPlaced: "Toutes les réservations de la fenêtre ont une place.",
    preassign: "Pré-affecter",
    preassignHint:
      "Donne une place à chaque réservation sans place : libre sur tout le séjour, près de la remise, retours groupés par rangée.",
    preassigned: (n: number, skipped: number) =>
      `${n} place${n > 1 ? "s" : ""} attribuée${n > 1 ? "s" : ""}${skipped ? ` · ${skipped} sans solution` : ""}`,
    stay: "Séjour",
    moveTo: "Déplacer vers",
    placeIn: "Placer en",
    choose: "Choisir…",
    noFree: "Aucune place libre sur ce séjour.",
    release: "Libérer la place",
    clickBar: "Cliquez un séjour pour le déplacer.",
    moved: (plate: string, code: string) => `${plate} placé en ${code}`,
    released: (plate: string) => `${plate} n'a plus de place`,
    spotTaken: "Cette place est déjà prise sur ces dates.",
    openBooking: "Ouvrir la réservation",
  },
  // Bloc 2, step "Occupation" (P-A, 04/10/2026): who is where, where the arrivals go.
  occupation: {
    title: "Occupation",
    intro:
      "Le plan en couleurs, les véhicules à placer et la recherche d'un véhicule par plaque, nom ou référence.",
    noPlan: "Générez d'abord les places dans le volet Plan.",
    search: "Rechercher un véhicule",
    searchPlaceholder: "Plaque, nom ou référence",
    noResult: "Aucun véhicule ne correspond.",
    legend: {
      occupied: "Occupée",
      leaving: "Départ aujourd'hui",
      booked: "Réservée (à venir)",
      free: "Libre",
      inactive: "Désactivée",
    },
    stats: (occupied: number, active: number, leaving: number) =>
      `${occupied} / ${active} places occupées · ${leaving} départ${leaving > 1 ? "s" : ""} aujourd'hui`,
    arrivals: (n: number) => `Arrivées à placer · ${n}`,
    stayZone: { short: "zone court séjour", medium: "zone moyen séjour", long: "zone long séjour" },
    noArrival: "Toutes les arrivées du jour ont une place.",
    suggested: (code: string) => `→ ${code} proposé`,
    reason: {
      near_handover: (m: number) => `à ${m} m de la remise`,
      near_entrance: (m: number) => `à ${m} m de l'entrée`,
      free: "libre pendant le séjour",
    },
    place: "Placer",
    chooseOnMap: "Choisir sur le plan",
    choosing: (plate: string) =>
      `Cliquez une place libre pour y mettre ${plate}.`,
    cancelChoice: "Annuler",
    spot: "Place",
    noSpot: "Pas de place",
    rowIndex: (row: number, index: number) => `Rangée ${row}, place ${index}`,
    keyHook: "Clés : crochet",
    keyHookPlaceholder: "n°",
    carPosition: (by: "traveller" | "staff", time: string, accuracy: number | null) =>
      `Position GPS ${by === "staff" ? "prise par l'équipe" : "donnée par le client"} à ${time}${accuracy !== null ? ` (± ${accuracy} m)` : ""}`,
    carDirections: "Itinéraire",
    legendCar: "Position GPS d'une voiture",
    saveKeys: "Enregistrer",
    returnOn: (date: string) => `Retour ${date}`,
    flight: (flight: string) => `vol ${flight}`,
    move: "Déplacer",
    release: "Libérer la place",
    placed: (plate: string, code: string) => `${plate} placé en ${code}`,
    released: (plate: string) => `${plate} n'a plus de place`,
    keysSaved: "Crochet enregistré",
    openBooking: "Ouvrir la réservation",
    freeSpot: "Place libre",
    clickSpot: "Cliquez une place sur le plan pour voir qui l'occupe.",
    bookedFor: (plate: string, date: string) => `${plate} attendu le ${date}`,
    spotTaken: "Cette place est déjà prise sur ces dates.",
  },
  // Bloc 2, step "Plan" (P-A, 03/10/2026): the operator's own parking plan.
  parkingPlan: {
    steps: ["Repérer le terrain", "Découper en zones", "Générer les places"],
    title: "Plan du parking",
    intro:
      "Tracez votre terrain sur la photo aérienne, découpez-le en zones, puis générez les places : la capacité déclarée se recalcule depuis les places actives.",
    saving: "Enregistrement…",
    saved: "Enregistré",
    saveError: "Non enregistré",
    layout: "Disposition",
    layouts: {
      selfPark: "Clients garés seuls",
      valet24: "Voiturier · files de 2 à 4",
      valet5: "Voiturier · files de 5",
      valetEdge: "Voiturier · files depuis le bord",
    },
    computing: "Calcul des dispositions…",
    places: (n: number) => `${n} place${n > 1 ? "s" : ""}`,
    // Z-A (04/10/2026): stay classes by rank in the file.
    stayZones: "Zones de séjour",
    stayClasses: {
      short: "Court séjour",
      medium: "Moyen séjour",
      long: "Long séjour",
    },
    stayClassesHelp: (short: number, medium: number) =>
      `Premier rang depuis l'allée : court séjour (jusqu'à ${short} nuits) ; fond de file : long séjour (plus de ${medium} nuits) ; entre les deux : moyen. La pré-affectation suit ces zones.`,
    stayClassCount: (n: number) => `${n}`,
    generate: "Générer les places",
    regenerate: "Régénérer les places",
    regenerateConfirm:
      "Régénérer remplace toutes les places et leurs réglages (places désactivées, types). Continuer ?",
    generated: (n: number) => `${n} places générées`,
    generatedOn: (date: string, layout: string) =>
      `Généré le ${date} · ${layout}`,
    noSpots:
      "Aucune place pour l'instant : choisissez une disposition et générez les places.",
    counts: "Places",
    countGenerated: "Générées",
    countActive: "Actives",
    countDeclared: "Capacité déclarée",
    applyCapacity: (n: number) => `Recalculer la capacité → ${n}`,
    capacityApplied: (n: number) => `Capacité déclarée : ${n} places`,
    capacityInSync: "Capacité déclarée à jour",
    adjust: "Ajuster à la main",
    adjustHelp:
      "Cliquez une place pour la désactiver ou la réactiver ; choisissez un type puis cliquez des places pour le leur donner.",
    tools: { toggle: "Activer / désactiver", kind: "Type de place" },
    spotKinds: {
      standard: "Standard",
      large: "Grand gabarit",
      covered: "Couverte",
      pmr: "PMR",
      reserved: "Réservée",
    },
    landmarks: "Repères",
    landmarksHelp:
      "Placez l'entrée, la sortie, la remise des clés, l'arrêt navette et la boîte à clés : ils servent aux distances et aux consignes.",
    landmarkKinds: {
      entrance: "Entrée",
      exit: "Sortie",
      handover: "Remise des clés",
      shuttle_stop: "Arrêt navette",
      key_box: "Boîte à clés",
    },
    placeLandmark: (kind: string) =>
      `Cliquez l'emplacement de « ${kind} » sur la carte.`,
    remove: "Retirer",
    back: "Retour",
    next: "Suivant",
    spotUpdated: "Place mise à jour",
    legend: { active: "Active", inactive: "Désactivée" },
    noZones: "Découpez d'abord le terrain en zones.",
  },
  platform: {
    brand: "Plateforme",
    tabs: {
      operators: "Loueurs",
      listings: "Annonces",
      reservations: "Réservations",
      payments: "Paiements",
      notifications: "Notifications",
      capacity: "Outil capacité",
    },
    notifications: {
      title: "Notifications",
      intro:
        "Un message push aux téléphones qui ont activé les notifications : le personnel de tous les parkings, les voyageurs qui ont une réservation en cours, ou l'équipe d'un seul loueur. À réserver aux informations utiles (incident, nouveauté, fermeture).",
      notConfigured: "OneSignal n'est pas configuré sur le serveur : l'envoi n'atteindra personne.",
      audience: "Destinataires",
      audiences: { staff: "Tout le personnel", travellers: "Tous les voyageurs", operator: "Un loueur" } as Record<PlatformAudience, string>,
      operator: "Loueur",
      operatorNone: "Choisir un loueur",
      titleField: "Titre",
      titlePlaceholder: "ex. Mise à jour de Plazo Pro",
      body: "Message",
      bodyPlaceholder: "ex. Une nouvelle version est disponible : mettez l'application à jour.",
      charsLeft: (n: number) => `${n} caractères restants.`,
      url: "Lien à l'ouverture (facultatif)",
      urlHelp: "Adresse https ouverte quand on touche la notification.",
      counting: "Comptage des téléphones…",
      reach: (n: number) => (n === 0 ? "Aucun téléphone à joindre" : `${n} téléphone${n > 1 ? "s" : ""} à joindre`),
      send: (n: number) => `Envoyer à ${n} téléphone${n > 1 ? "s" : ""}`,
      confirmTitle: "Confirmer l'envoi",
      confirm: (n: number, audience: string) => `Envoyer ce message à ${n} téléphone${n > 1 ? "s" : ""} (${audience.toLowerCase()}) ? Il ne peut pas être rappelé.`,
      confirmYes: "Envoyer",
      cancel: "Annuler",
      travellersLimit: "Voyageurs : deux envois par jour au plus.",
      sent: (n: number) => `Envoyé à ${n} téléphone${n > 1 ? "s" : ""}.`,
      history: "Envois précédents",
      historyEmpty: "Aucun envoi pour le moment.",
      colWhen: "Date",
      colAudience: "Destinataires",
      colMessage: "Message",
      colRecipients: "Téléphones",
      colBy: "Par",
    },
    view: "Vue :",
    viewAll: "Toute la plateforme",
    viewOwn: (name: string) => `Mon espace (${name})`,
    viewMenu: "Changer de vue",
    logout: "Se déconnecter",
    operators: {
      title: "Loueurs",
      invite: "+ Inviter un loueur",
      colOperator: "Loueur",
      colManager: "Gérant",
      colListing: "Annonce",
      colPayments: "Paiements",
      colCommission: "Commission",
      colBookings: "Résa. du mois",
      parkingsPlaces: (parkings: number, places: number) =>
        `${parkings} parking${parkings > 1 ? "s" : ""} · ${places} places`,
      invitedOn: (date: string) => `invitation envoyée le ${date}`,
      invitationExpired: (date: string) =>
        `invitation expirée (envoyée le ${date})`,
      suspendedOn: (date: string) => `suspendu le ${date}`,
      platformAccount: "compte de la plateforme",
      emailToConfirm: "email à confirmer",
      paymentsActive: "Actifs",
      paymentsToActivate: "À activer",
      paymentsNone: "Non connectés",
      noListing: "Pas de fiche",
      defaultCommission: (pct: string) => `${pct} % (défaut)`,
      noCommission: "à définir",
      open: "Ouvrir son espace ›",
      resend: "Renvoyer l'invitation",
      resent: "Invitation renvoyée.",
      suspend: "Suspendre",
      reactivate: "Réactiver",
      confirmSuspend: (name: string) =>
        `Suspendre ${name} ? Son équipe sera déconnectée et ne pourra plus se connecter, et ses fiches seront retirées du site.`,
      suspended: "Loueur suspendu.",
      reactivated: "Loueur réactivé.",
      editCommission: (name: string) => `Modifier la commission de ${name}`,
      commissionLabel: "Commission (%)",
      commissionSaved: "Commission enregistrée.",
      commissionHelp: "Vide : taux par défaut de la plateforme.",
      cancel: "Annuler",
      save: "Enregistrer",
      empty: "Aucun loueur pour l'instant.",
      statusSuspended: "Suspendu",
      statusDemo: "Démo",
      demoHint: "Loueur fictif créé par les données de démonstration",
      inviteTitle: "Inviter un loueur",
      inviteName: "Nom de l'entreprise / du parking",
      inviteEmail: "Email du gérant",
      inviteCapacity: "Capacité (places)",
      inviteCommission: (pct: string | null) =>
        pct ? `Commission (par défaut ${pct} %)` : "Commission (%)",
      inviteSubmit: "Envoyer l'invitation",
      inviteHelp:
        "Le gérant reçoit un email avec un lien (valable 7 jours) pour choisir son mot de passe. Personne d'autre ne connaît son mot de passe.",
      invited: "Invitation envoyée.",
      linkTitle: "L'email n'a pas pu partir",
      linkWarning:
        "L'envoi d'emails n'est pas configuré. Copiez ce lien et transmettez-le vous-même au gérant : il ne sera plus affiché. Il est valable 7 jours et ne sert qu'une fois.",
      copy: "Copier le lien",
      copied: "Lien copié.",
      close: "Fermer",
      canDoTitle: "Ce que vous pouvez faire sur un loueur",
      canDo: [
        "Valider / dépublier son annonce",
        "Régler sa commission",
        "Ouvrir son espace (bandeau jaune « Vous consultez l'espace de … »), actions tracées dans le journal",
        "Suspendre le compte",
      ],
    },
    listings: {
      title: "Annonces",
      filters: {
        pending_review: "À valider",
        published: "Publiées",
        rejected: "Refusées",
        draft: "Brouillons",
        all: "Toutes",
      },
      empty: "Aucune annonce dans cette liste.",
      submittedOn: (date: string) => `envoyée le ${date}`,
      updatedOn: (date: string) => `modifiée le ${date}`,
      approve: "Valider",
      reject: "Refuser",
      unpublish: "Dépublier",
      details: "Voir la fiche",
      hideDetails: "Masquer la fiche",
      approved: "Annonce publiée.",
      rejected: "Annonce refusée. Le loueur voit votre message sur sa fiche.",
      unpublished: "Annonce dépubliée.",
      rejectLabel: "Message au loueur (obligatoire)",
      rejectPlaceholder: "Ce qu'il faut corriger avant la mise en ligne…",
      unpublishLabel: "Message au loueur (facultatif)",
      confirmReject: "Refuser l'annonce",
      confirmUnpublish: "Dépublier l'annonce",
      cancel: "Annuler",
      previewNote:
        "Aperçu tel qu'il apparaîtra dans les résultats ; la page publique n'existe qu'une fois l'annonce validée.",
      viewPage: "Voir la page publique",
      operatorSuspended: "loueur suspendu",
      address: "Adresse",
      description: "Présentation",
      prices: "Tarifs",
      noPrices: "Aucun tarif enregistré.",
      upTo: (days: number, price: string) => `Jusqu'à ${days} j : ${price}`,
      photos: "Photos",
      noPhoto: "Aucune photo.",
      lastMessage: "Dernier message envoyé",
      places: (n: number) => `${n} places`,
    },
    reservations: {
      title: "Réservations",
      operator: "Loueur",
      allOperators: "Tous les loueurs",
      from: "Arrivée du",
      to: "au",
      colArrival: "Arrivée",
      colOperator: "Loueur",
      colParking: "Parking",
      colReference: "Référence",
      colPlate: "Plaque",
      colStatus: "Statut",
      colAmount: "Montant",
      colChannel: "Canal",
      empty: "Aucune réservation pour ces filtres.",
      total: (n: number) => `${n} réservation${n > 1 ? "s" : ""}`,
      privacy:
        "Lecture seule. Les coordonnées des voyageurs ne sont pas affichées ici.",
      pendingPayment: "Paiement en cours",
    },
    payments: {
      title: "Paiements",
      disabled:
        "Le paiement en ligne n'est pas activé (pas de clé Stripe) : les voyageurs paient au parking.",
      colOperator: "Loueur",
      colStripe: "Stripe",
      colSchedule: "Reversement",
      colPending: "En attente",
      colFailed: "En échec",
      stripeActive: "Virements actifs",
      stripeIncomplete: "Inscription à finir",
      stripeNone: "Non connecté",
      pending: (n: number, amount: string) => (n ? `${n} · ${amount}` : "—"),
      none: "—",
      retry: "Relancer",
      retried: {
        transferred: "Reversement effectué.",
        failed: "Stripe refuse encore ce virement.",
        skipped: "Virement reporté : il sera retenté par la tâche quotidienne.",
      },
      failedRow: (reference: string, amount: string) =>
        `${reference} · ${amount}`,
      readOnly:
        "Lecture seule. Un reversement refusé par Stripe peut être relancé.",
    },
    payoutSchedule: {
      AFTER_STAY: "Le lendemain du séjour",
      AT_DROP_OFF: "Le lendemain du dépôt",
      WEEKLY: "Chaque lundi",
      MONTHLY: "Le 1er du mois",
    } satisfies Record<PayoutSchedule, string>,
  },
  notFound: {
    title: "Page introuvable",
    back: "Retour au tableau de bord",
  },
};

export function errorMessage(code: string | undefined): string {
  if (!code) return fr.errors.unknown;
  return fr.errors[code] ?? fr.errors.unknown;
}

/** French message for any error thrown by the API client. */
export function describeError(error: unknown): string {
  if (error instanceof ApiError) return errorMessage(error.code);
  if (error instanceof TypeError) return fr.errors.network;
  return fr.errors.unknown;
}

export const dateTime = new Intl.DateTimeFormat("fr-FR", {
  dateStyle: "short",
  timeStyle: "short",
  timeZone: "Europe/Paris",
});

export const flightCheckFr = {
  title: "Tester le suivi de vol",
  intro: "Interroge le fournisseur de suivi de vols pour un vol et une date, et montre sa réponse telle quelle.",
  flight: "Numéro de vol",
  date: "Date (locale)",
  role: "Côté",
  arrival: "Atterrissage à l'aéroport (vol retour)",
  departure: "Décollage de l'aéroport (vol aller)",
  run: "Interroger",
  running: "Interrogation…",
  provider: (provider: string, host: string | null) => `Fournisseur : ${provider}${host ? ` · ${host}` : ""}`,
  outcome: {
    not_configured: "Aucun fournisseur configuré : ajoutez AERODATABOX_API_KEY (ou AIRLABS_API_KEY) sur Vercel.",
    found: "Vol trouvé.",
    not_found: "Le fournisseur ne connaît pas ce vol à cette date (vérifiez le numéro et la date).",
    error: "Le fournisseur a refusé la demande.",
  } as Record<string, string>,
  errorHint: (error: string) =>
    /403/.test(error)
      ? `${error} — clé refusée ou endpoint hors forfait : sur RapidAPI, vérifiez l'abonnement au plan Basic d'AeroDataBox et la clé X-RapidAPI-Key.`
      : /401/.test(error)
        ? `${error} — clé invalide.`
        : /429/.test(error)
          ? `${error} — quota du forfait épuisé.`
          : error,
  fields: {
    status: "Statut",
    scheduled: "Prévu",
    estimated: "Révisé",
    actual: "Réel",
    airport: "Aéroport",
    terminal: "Terminal",
    gate: "Porte",
  },
};

export const shuttleWavesFr = {
  title: "Navettes",
  wavesTitle: "Ligne du jour",
  subtitle: "Ligne du jour : quand chaque navette doit partir, avec combien de passagers.",
  today: "Aujourd'hui",
  tomorrow: "Demain",
  dayAfter: (day: string) => day,
  refreshed: (ago: string) => `Actualisé ${ago}`,
  loadError: "Impossible de charger la prévision des navettes.",
  empty: "Aucune navette à prévoir ce jour-là.",
  seats: (seats: number | null, vehicles: number) =>
    seats === null ? `${vehicles} véhicule${vehicles > 1 ? "s" : ""} en service · places inconnues` : `${vehicles} véhicule${vehicles > 1 ? "s" : ""} en service · ${seats} places`,
  times: (lead: number, delay: number, travel: number) =>
    `Au terminal ${lead} min avant le décollage · rendez-vous ${delay} min après l'atterrissage · trajet ${travel} min`,
  settings: "Modifier les délais",
  wave: {
    count: (n: number) => `${n} vague${n > 1 ? "s" : ""}`,
    direction: { dropoff: "Vers le terminal", pickup: "Depuis l'aéroport" } satisfies Record<ShuttleDirection, string>,
    airport: "Aéroport",
    passengers: (n: number, seats: number | null) => (seats === null ? `${n}` : `${n} / ${seats}`),
    vehicles: (n: number) => `${n} navettes`,
    meetAt: (time: string) => `rendez-vous ${time}`,
    noFlight: (n: number) => (n === 1 ? "1 sans vol" : `${n} sans vol`),
    state: { planned: "À venir", running: "En cours", done: "Faite" } satisfies Record<WaveState, string>,
    pax: (n: number) => `${n} pass.`,
    flight: {
      scheduled: "à l'heure",
      delayed: (minutes: number) => `retardé +${minutes}`,
      departed: "parti",
      landed: "atterri",
      cancelled: "annulé",
      diverted: "dérouté",
      unknown: "vol inconnu",
      none: "heure saisie",
    },
    takeOff: (time: string) => `décollage ${time}`,
    landing: (time: string) => `atterrissage ${time}`,
    bookingTime: (time: string) => `heure saisie ${time}`,
  },
};

/** The driver's part of the Navettes page (06/10/2026): the same trips as the Plazo Pro app. */
export const shuttleTripsFr = {
  card: "Fiche du client",
  live: {
    title: "Navettes en cours",
    none: "Aucune navette en route pour le moment.",
    passengers: (n: number) => `${n} client${n > 1 ? "s" : ""}`,
    since: (time: string) => `partie à ${time}`,
    noPosition: "position en attente",
    toStop: (name: string, min: number) => `${name} dans ${min} min`,
    toParking: (min: number) => `parking dans ${min} min`,
    end: "Terminer ce trajet",
    endConfirm: (driver: string) => `Terminer le trajet de ${driver} ? Sa position ne sera plus partagée.`,
  },
  running: {
    pickup: "En route vers l'aéroport · position partagée",
    dropoff: "En route vers le terminal · position partagée",
    stop: (name: string) => `Desserte : ${name}`,
    vehicle: (v: string) => `Véhicule : ${v}`,
    passengers: (n: number) => `${n} client${n > 1 ? "s" : ""} suivent votre trajet`,
    left: (m: number) => `arrêt automatique dans ${m} min`,
    endPickup: "Clients récupérés · retour parking",
    endDropoff: "Clients déposés · retour parking",
    ended: "Trajet terminé : votre position n'est plus partagée et a été effacée.",
    locationDenied: "Sans accès à la position, les clients ne verront pas la navette avancer. Autorisez la position dans le navigateur.",
    sharing: "Position partagée",
    noGeolocation: "Ce navigateur ne donne pas la position : le trajet est visible sans sa position.",
  },
  start: {
    title: "Démarrer un trajet",
    introPickup: "Vos clients de retour, à récupérer à l'aéroport. Démarrez le trajet : ils suivent votre position.",
    introDropoff: "Vos clients arrivés au parking, à conduire au terminal. Démarrez le trajet : ils suivent votre position.",
    direction: { pickup: "Retours · aéroport", dropoff: "Départs · terminal" } satisfies Record<ShuttleDirection, string>,
    stop: "Desserte",
    airport: "Aéroport",
    meetingPoint: (label: string) => `Point de rendez-vous : ${label}`,
    meetingPointNone: "Point de rendez-vous : l'aéroport (à définir dans Parking › Réglages).",
    toPickUp: (terminal: string) => `À récupérer · ${terminal}`,
    noTerminal: "Terminal",
    toDropOff: "À conduire au terminal",
    emptyPickup: "Aucun retour à récupérer pour le moment.",
    emptyDropoff: "Aucun client arrivé n'attend la navette.",
    pax: (n: number) => `${n} pass.`,
    flight: (n: string) => `vol ${n}`,
    gate: (g: string) => `Porte ${g}`,
    arrivedAt: (t: string) => `Arrivé ${t}`,
    arrivalPlanned: (t: string) => `Arrivée prévue ${t}`,
    spot: (code: string) => `Place ${code}`,
    badge: {
      onTrip: "Sur un trajet",
      atPoint: (t: string) => `Au point de RDV ${t}`,
      landed: (t: string) => `Atterri ${t} · en chemin`,
      cancelled: "Vol annulé",
      returnAt: (t: string) => `Retour prévu ${t}`,
      delayed: (t: string) => `Retardé · ${t}`,
      planned: (t: string) => `Vol prévu ${t}`,
    },
    vehicle: "Véhicule",
    vehicleFree: "Autre véhicule",
    vehicleSeats: (n: number) => `${n} places`,
    vehicleOut: "hors service",
    vehicleModel: "Modèle",
    vehicleColour: "Couleur",
    vehiclePlate: "Plaque",
    vehicleHelp: "Vos clients verront ce véhicule et votre prénom.",
    tooMany: (p: number, seats: number) => `${p} passagers pour ${seats} places : choisissez un autre véhicule ou moins de clients.`,
    none: "Sélectionnez des clients",
    pickup: (n: number) => (n === 1 ? "Partir à l'aéroport · 1 client" : `Partir à l'aéroport · ${n} clients`),
    dropoff: (n: number) => (n === 1 ? "Partir au terminal · 1 client" : `Partir au terminal · ${n} clients`),
    starting: "Démarrage…",
    needsStatus: "Seuls les chauffeurs, voituriers, agents et gérants peuvent démarrer un trajet.",
    loadError: "Impossible de charger les clients à transporter.",
  },
};

/** The operational card (C-A, 06/10/2026): the same short sheet from Planning, Navettes and Occupation, with the next gesture. */
export const quickCardFr = {
  title: "Fiche",
  close: "Fermer",
  open: "Ouvrir la fiche complète",
  call: "Appeler",
  sms: "SMS",
  loadError: "Impossible de charger la réservation.",
  arrival: "Dépôt",
  return: "Retour",
  flight: "Vol retour",
  departureFlight: "Vol aller",
  noFlight: "sans vol",
  flightState: {
    landed: (t: string) => `atterri ${t}`,
    delayed: (t: string) => `retardé · ${t}`,
    cancelled: "annulé",
    diverted: "dérouté",
    scheduled: (t: string) => `prévu ${t}`,
    unknown: "vol inconnu",
  },
  terminal: (t: string) => `Terminal ${t}`,
  gate: (g: string) => `porte ${g}`,
  spot: "Place",
  noSpot: "pas de place",
  keys: "Clés",
  noKeys: "crochet non noté",
  car: "Voiture",
  carDirections: "itinéraire",
  stop: "Desserte",
  passengers: (n: number) => `${n} pass.`,
  notes: "Notes",
  next: {
    title: "Prochaine étape",
    place: "Placer la voiture",
    placeHelp: "Sur le plan, avec le crochet des clés : le client passe « Sur place ».",
    dropOff: "Déposer au terminal",
    dropOffHelp: "Ouvre la navette, côté départs, avec ce client sélectionné.",
    pickUp: "Récupérer à l'aéroport",
    pickUpHelp: "Ouvre la navette, côté retours, avec ce client sélectionné.",
    handOver: "Rendre le véhicule",
    handOverHelp: "Clés rendues, état du véhicule, remarque éventuelle.",
    closed: "Réservation close.",
    more: "Autres actions…",
    confirmCancel: "Annuler cette réservation ? Le client ne sera pas attendu.",
    confirmNoShow: "Marquer le client comme non venu ?",
  },
  handover: {
    title: "Rendre le véhicule",
    keys: "Clés rendues au client",
    keysHelp: "Le crochet est libéré.",
    keysRequired: "Confirmez que les clés sont rendues.",
    note: "Remarque (dégât, litige, objet oublié…)",
    noteHint: "Facultatif · gardée dans les notes, datée et signée",
    confirm: "Véhicule rendu",
    back: "Retour",
  },
};
