import 'package:dio/dio.dart';
import 'package:get_it/get_it.dart';
import 'package:logger/logger.dart';

import '../core/constants/app_constants.dart';
import '../core/networking/networking.dart';
import '../core/router/app_router.dart';
import '../core/router/pro_auth_guard.dart';
import '../features/arrival/data/client/arrival_client.dart';
import '../features/arrival/data/datasources/arrival_data_source.dart';
import '../features/arrival/domain/repositories/arrival_repository.dart';
import '../features/arrival/domain/usecases/announce_arrival_use_case.dart';
import '../features/arrival/domain/usecases/at_meeting_point_use_case.dart';
import '../features/arrival/domain/usecases/get_arrival_use_case.dart';
import '../features/arrival/domain/usecases/send_position_use_case.dart';
import '../features/arrival/domain/usecases/start_sharing_use_case.dart';
import '../features/arrival/domain/usecases/stop_sharing_use_case.dart';
import '../features/arrival/presentation/bloc/arrival_bloc.dart';
import '../features/booking/data/client/booking_client.dart';
import '../features/booking/data/datasources/booking_data_source.dart';
import '../features/booking/domain/repositories/booking_repository.dart';
import '../features/booking/domain/usecases/booking_actions_use_cases.dart';
import '../features/booking/domain/usecases/forget_booking_use_case.dart';
import '../features/booking/domain/usecases/get_booking_use_case.dart';
import '../features/booking/domain/usecases/lookup_booking_use_case.dart';
import '../features/booking/domain/usecases/save_booking_access_use_case.dart';
import '../features/booking/domain/usecases/saved_bookings_use_case.dart';
import '../features/booking/presentation/bloc/booking_bloc.dart';
import '../features/booking/presentation/bloc/car_location_bloc.dart';
import '../features/checkout/domain/booking_draft.dart';
import '../features/checkout/presentation/bloc/booking_form_bloc.dart';
import '../features/checkout/presentation/bloc/payment_bloc.dart';
import '../features/pro_auth/data/client/auth_client.dart';
import '../features/pro_auth/data/datasources/auth_data_source.dart';
import '../features/pro_auth/domain/repositories/auth_repository.dart';
import '../features/pro_auth/domain/usecases/login_use_case.dart';
import '../features/pro_auth/domain/usecases/logout_use_case.dart';
import '../features/pro_auth/domain/usecases/restore_session_use_case.dart';
import '../features/pro_auth/domain/usecases/set_post_use_case.dart';
import '../features/pro_auth/domain/usecases/set_vehicle_use_case.dart';
import '../features/pro_auth/presentation/bloc/pro_auth_bloc.dart';
import '../features/pro_notifications/data/client/notifications_client.dart';
import '../features/pro_notifications/data/datasources/notifications_data_source.dart';
import '../features/pro_notifications/domain/repositories/notifications_repository.dart';
import '../features/pro_notifications/domain/usecases/enable_push_use_case.dart';
import '../features/pro_notifications/domain/usecases/get_notification_preferences_use_case.dart';
import '../features/pro_notifications/domain/usecases/update_notification_preferences_use_case.dart';
import '../features/pro_notifications/presentation/bloc/pro_notifications_bloc.dart';
import '../features/pro_occupation/data/client/occupation_client.dart';
import '../features/pro_occupation/data/datasources/occupation_data_source.dart';
import '../features/pro_occupation/domain/repositories/occupation_repository.dart';
import '../features/pro_occupation/domain/usecases/occupation_use_cases.dart';
import '../features/pro_occupation/presentation/bloc/pro_occupation_bloc.dart';
import '../features/pro_plan/data/client/plan_client.dart';
import '../features/pro_reservations/data/client/reservations_client.dart';
import '../features/pro_reservations/data/datasources/reservations_data_source.dart';
import '../features/pro_reservations/domain/repositories/reservations_repository.dart';
import '../features/pro_reservations/domain/usecases/reservations_use_cases.dart';
import '../features/pro_reservations/presentation/bloc/pro_import_bloc.dart';
import '../features/pro_reservations/presentation/bloc/pro_reservation_bloc.dart';
import '../features/pro_reservations/presentation/bloc/pro_reservations_bloc.dart';
import '../features/pro_plan/data/datasources/plan_data_source.dart';
import '../features/pro_shuttle/presentation/bloc/pro_vehicles_bloc.dart';
import '../features/return_day/presentation/bloc/stay_shuttles_bloc.dart';
import '../features/pro_plan/domain/repositories/plan_repository.dart';
import '../features/pro_plan/domain/usecases/plan_use_cases.dart';
import '../features/pro_plan/presentation/bloc/pro_plan_bloc.dart';
import '../features/pro_spot_planning/data/client/spot_planning_client.dart';
import '../features/pro_spot_planning/data/datasources/spot_planning_data_source.dart';
import '../features/pro_spot_planning/domain/repositories/spot_planning_repository.dart';
import '../features/pro_spot_planning/domain/usecases/spot_planning_use_cases.dart';
import '../features/pro_spot_planning/presentation/bloc/pro_spot_planning_bloc.dart';
import '../features/pro_settings/data/client/settings_client.dart';
import '../features/pro_settings/data/datasources/settings_data_source.dart';
import '../features/pro_settings/domain/repositories/settings_repository.dart';
import '../features/pro_settings/domain/usecases/settings_use_cases.dart';
import '../features/pro_settings/presentation/bloc/pro_settings_bloc.dart';
import '../features/pro_settings/presentation/bloc/pro_team_bloc.dart';
import '../features/pro_shuttle/data/client/shuttle_client.dart';
import '../features/pro_shuttle/data/datasources/shuttle_data_source.dart';
import '../features/pro_shuttle/domain/repositories/shuttle_repository.dart';
import '../features/pro_shuttle/domain/usecases/shuttle_use_cases.dart';
import '../features/pro_shuttle/presentation/bloc/shuttle_bloc.dart';
import '../features/pro_shuttle/presentation/bloc/live_shuttles_bloc.dart';
import '../features/pro_shuttle/presentation/bloc/shuttle_waves_bloc.dart';
import '../features/pro_dashboard/data/client/dashboard_client.dart';
import '../features/pro_dashboard/data/datasources/dashboard_data_source.dart';
import '../features/pro_dashboard/domain/repositories/dashboard_repository.dart';
import '../features/pro_dashboard/domain/usecases/get_dashboard_use_case.dart';
import '../features/pro_dashboard/presentation/bloc/pro_dashboard_bloc.dart';
import '../features/pro_today/data/client/planning_client.dart';
import '../features/pro_today/data/datasources/planning_data_source.dart';
import '../features/pro_today/domain/repositories/planning_repository.dart';
import '../features/pro_today/domain/usecases/get_live_arrivals_use_case.dart';
import '../features/pro_today/domain/usecases/get_planning_use_case.dart';
import '../features/pro_today/presentation/bloc/pro_today_bloc.dart';
import '../features/return_day/data/client/return_client.dart';
import '../features/return_day/data/datasources/return_data_source.dart';
import '../features/return_day/domain/repositories/return_repository.dart';
import '../features/return_day/domain/usecases/return_use_cases.dart';
import '../features/return_day/presentation/bloc/meeting_route_bloc.dart';
import '../features/return_day/presentation/bloc/return_bloc.dart';
import '../features/search/data/client/public_client.dart';
import '../features/search/data/datasources/public_data_source.dart';
import '../features/search/domain/repositories/public_repository.dart';
import '../features/search/domain/usecases/public_use_cases.dart';
import '../features/search/presentation/bloc/parking/parking_bloc.dart';
import '../features/search/presentation/bloc/results/results_bloc.dart';
import '../features/search/presentation/bloc/search/search_bloc.dart';
import '../features/trips/presentation/bloc/manage_booking_bloc.dart';
import '../features/trips/presentation/bloc/trips_bloc.dart';
import '../services/link_service.dart';
import '../services/location_service.dart';
import '../services/payment_sheet_service.dart';
import '../services/push_service.dart';
import '../services/secure_storage_service.dart';

part 'bloc_locator.dart';
part 'client_locator.dart';
part 'data_source_locator.dart';
part 'external_locator.dart';
part 'repository_locator.dart';
part 'service_locator.dart';
part 'use_case_locator.dart';

final locator = GetIt.instance;

Future<void> initLocator() async {
  _initServices();
  _initExternal();
  _initClients();
  _initDataSource();
  _initRepositoryLocator();
  _initUseCaseLocator();
  _initBlocs();
}
