// GENERATED by tool/sync_product.dart from ../product.json. Do not edit by hand.

/// The product name is still a working name: it lives only in the repository's product.json.
abstract final class Product {
  static const name = 'Plazo';
  static const proName = 'Plazo Pro';
  static const tagline = 'Gestion de parkings d\'aéroport';
  static const supportEmail = 'support@example.com';
}
