// Copies the product name from the repository's product.json (its only home: it may still change)
// into the app: a Dart constant, the Android label, the iOS display name (APP_DISPLAY_NAME of the Xcode
// build configurations, read by Info.plist) and the web title.
//
//   dart run tool/sync_product.dart          # write
//   dart run tool/sync_product.dart --check  # exit 1 when something is out of date (CI)
import 'dart:convert';
import 'dart:io';

void main(List<String> args) {
  final check = args.contains('--check');
  final product = jsonDecode(File('../product.json').readAsStringSync()) as Map<String, dynamic>;
  final name = product['name'] as String;
  final tagline = product['tagline'] as String;
  final supportEmail = product['supportEmail'] as String;
  String esc(String v) => v.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll(r'$', r'\$');
  String xml(String v) => v.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('"', '&quot;');
  String pbx(String v) => v.replaceAll(r'\', r'\\').replaceAll('"', r'\"');

  final edits = <String, String Function(String)>{
    'lib/src/core/constants/product.g.dart': (_) => '''// GENERATED by tool/sync_product.dart from ../product.json. Do not edit by hand.

/// The product name is still a working name: it lives only in the repository's product.json.
abstract final class Product {
  static const name = '${esc(name)}';
  static const proName = '${esc(name)} Pro';
  static const tagline = '${esc(tagline)}';
  static const supportEmail = '${esc(supportEmail)}';
}
''',
    // Android: one label per flavor (the manifest reads @string/app_name).
    'android/app/build.gradle.kts': (s) => s
        .replaceFirstMapped(RegExp(r'create\("traveller"\) \{\s*dimension = "app"\s*applicationId = "[^"]*"\s*resValue\("string", "app_name", "[^"]*"\)'), (m) => m[0]!.replaceFirst(RegExp(r'"app_name", "[^"]*"'), '"app_name", "${esc(name)}"'))
        .replaceFirstMapped(RegExp(r'create\("pro"\) \{\s*dimension = "app"\s*applicationId = "[^"]*"\s*resValue\("string", "app_name", "[^"]*"\)'), (m) => m[0]!.replaceFirst(RegExp(r'"app_name", "[^"]*"'), '"app_name", "${esc(name)} Pro"')),
    // iOS: Info.plist reads $(APP_DISPLAY_NAME); each Xcode build configuration sets it, "<name> Pro" for the
    // -pro ones (Plazo Pro) and "<name>" for the others.
    'ios/Runner.xcodeproj/project.pbxproj': (s) => s.replaceAllMapped(
        RegExp(r'APP_DISPLAY_NAME = "?([^";\n]*?)"?;'),
        (m) => 'APP_DISPLAY_NAME = "${pbx(m[1]!.endsWith(' Pro') ? '$name Pro' : name)}";'),
    'web/index.html': (s) => s
        .replaceFirst(RegExp(r'<title>[^<]*</title>'), '<title>${xml(name)}</title>')
        .replaceFirstMapped(RegExp(r'(name="apple-mobile-web-app-title" content=")[^"]*'), (m) => '${m[1]}${xml(name)}'),
    'web/manifest.json': (s) => s
        .replaceFirst(RegExp(r'"name": "[^"]*"'), '"name": "${xml(name)}"')
        .replaceFirst(RegExp(r'"short_name": "[^"]*"'), '"short_name": "${xml(name)}"'),
  };

  var outdated = false;
  edits.forEach((path, edit) {
    final file = File(path);
    final before = file.existsSync() ? file.readAsStringSync() : '';
    final after = edit(before);
    if (after == before) return;
    outdated = true;
    if (check) {
      stderr.writeln('$path is out of date: run `dart run tool/sync_product.dart`');
    } else {
      file.writeAsStringSync(after);
      stdout.writeln('updated $path');
    }
  });
  if (check && outdated) exit(1);
}
